In [30]:
import pandas as pd
import matplotlib as plt
from metrics import metrics
from model import generics
pd.set_option('display.max_rows', 2000)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [102]:
experiment_id = 'pertexps'

In [103]:
df_mean_metrics, df_all_metrics, df_prevs = metrics.open_fold_result(experiment_id)

In [104]:
df_mean_metrics#[df_mean_metrics.reset_index()['model'].str.contains("mlp-").values]

                                       MSE          RMSE         MAPE  \
ts            model
Unemployment  arima           2.978551e+03     54.576100     7.012015
              mlpgs           1.317445e+03     36.253273     4.530343
              mlpkpssfalse    1.257599e+03     35.441220     4.490128
              mlpkpssfalsep1  1.263940e+03     35.533396     4.273653
              mlpkpssfalsep2  1.194990e+03     34.556246     4.218171
              mlpkpssfalsep3  1.378923e+03     37.112143     4.474092
              mlpwk0.61005    1.328637e+03     36.422281     4.314731
              mlpwk11005      1.250247e+03     35.326696     4.202943
              svrgs           1.935252e+03     43.991502     5.363710
              svrwk0.6505     2.234920e+03     47.274940     5.726779
ausbee        arima           1.851701e+02     13.607720     2.445095
              mlpgs           2.634443e+02     16.224474     2.871810
              mlpkpssfalse    2.495322e+02     15.773261     2.765758
              mlpkpssfalsep1  3.166997e+02     17.790413     3.203947
              mlpkpssfalsep2  3.310681e+02     18.188745     3.312143
              mlpkpssfalsep3  3.571557e+02     18.894978     3.525176
              mlpwk0.61005    1.002970e+04     90.301617    16.096839
              mlpwk11005      1.370786e+03     34.660087     6.251220
              svrgs           3.635586e+02     19.067212     3.483389
              svrwk0.6505     1.505774e+06   1227.099833   285.810532
austres       arima           2.925290e+02     17.103479     0.075877
              mlpgs           3.158341e+02     17.771329     0.074567
              mlpkpssfalse    2.121747e+03     42.316535     0.230565
              mlpkpssfalsep1  3.030502e+02     17.404905     0.084490
              mlpkpssfalsep2  3.213592e+02     17.887057     0.086218
              mlpkpssfalsep3  3.658122e+02     19.054031     0.092524
              mlpwk0.61005    3.188609e+02     17.844809     0.086432
              mlpwk11005      3.190547e+02     17.839236     0.086425
              svrgs           3.348059e+02     18.297702     0.080785
              svrwk0.6505     3.251646e+08  18032.321671   104.370228
coloradoRiver arima           2.769386e-01      0.526250    93.935436
              mlpgs           2.483630e-01      0.498215    77.226950
              mlpkpssfalse    2.497202e-01      0.499563   100.738194
              mlpkpssfalsep1  2.252985e-01      0.474559    92.121111
              mlpkpssfalsep2  2.175353e-01      0.466346    85.285856
              mlpkpssfalsep3  2.210226e-01      0.469983    87.321495
              mlpwk0.61005    2.262175e-01      0.475285    83.075292
              mlpwk0.81005    2.289332e-01      0.478271    90.387409
              mlpwk11005      2.204369e-01      0.468930    87.788905
              svrgs           2.639992e-01      0.513808    68.067915
              svrwk0.6505     3.377271e+02     18.377352  2998.796556
gasoline      arima           5.964224e+04    244.217611     2.216460
              mlpgs           6.120519e+04    247.394586     2.194634
              mlpkpssfalse    6.414784e+04    253.272202     2.319554
              mlpkpssfalsep1  6.548213e+04    255.878632     2.345376
              mlpkpssfalsep2  6.645167e+04    257.773694     2.361211
              mlpkpssfalsep3  6.672063e+04    258.286232     2.366742
              mlpwk0.61005    6.913146e+04    262.787022     2.410329
              mlpwk11005      7.014855e+04    264.696197     2.430625
              svrgs           6.340822e+04    251.809890     2.203433
heartrate     arima           4.069414e-01      0.637920     0.594484
              mlpgs           1.089161e+00      1.027196     1.016918
              mlpkpssfalse    8.209328e-01      0.898068     0.862110
              mlpkpssfalsep1  1.093174e+00      1.005461     0.916356
              mlpkpssfalsep2  1.079873e+00      0.975090     0.870213
              mlpkpssfalsep3  1.094295e+00      1.008897     0.957090
              mlpwk0.61005    1.059869e+01      2.207718     1.900046
              mlpwk11005      4.662120e-01      0.681890     0.618728
              svrgs           1.038407e+00      1.019023     0.961778
              svrwk0.6505     1.138280e+00      1.066902     0.905311
milk          arima           3.218855e+01      5.673496     0.521295
              mlpgs           3.240672e+01      5.690461     0.539788
              mlpkpssfalse    1.264999e+02     11.108655     1.077478
              mlpkpssfalsep1  2.707578e+02     14.927683     1.350429
              mlpkpssfalsep2  6.250221e+02     21.561323     1.879050
              mlpkpssfalsep3  9.564140e+02     25.620603     2.295933
              mlpwk0.61005    6.970568e+02     24.415674     2.244956
              mlpwk11005      4.756213e+02     14.707015     1.297057
              svrgs           3.055180e+01      5.527368     0.530865
              svrwk0.6505     6.734040e+04    259.500295    25.817840
ozon          arima           8.166000e-01      0.903659    17.818441
              mlpgs           1.025814e+00      1.011815    18.991299
              mlpkpssfalse    1.028138e+00      1.013772    19.231159
              mlpkpssfalsep1  9.494361e-01      0.974374    18.944924
              mlpkpssfalsep2  1.009161e+00      1.004565    19.403506
              mlpkpssfalsep3  1.739559e+00      1.300874    26.312933
              mlpwk0.61005    9.536004e-01      0.976462    18.560638
              mlpwk11005      9.235336e-01      0.960993    18.590709
              svrgs           7.290218e-01      0.853828    15.862582
              svrwk0.6505     2.398062e+01      4.897001    97.295330
pollution     arima           6.739643e+05    820.953307    23.080686
              mlpgs           5.354766e+05    731.592903    20.792957
              mlpkpssfalse    4.734050e+05    687.789533    17.871604
              mlpkpssfalsep1  1.017461e+06    932.254999    24.782521
              mlpkpssfalsep2  1.253094e+06   1034.335529    28.637476
              mlpkpssfalsep3  7.135611e+05    801.102545    21.827787
              mlpwk0.61005    5.282170e+05    726.467167    19.589446
              mlpwk11005      6.587703e+05    810.635773    22.307844
              svrgs           4.684015e+05    684.398630    18.847271
              svrwk0.6505     5.981690e+06   2445.749476    70.023966
redwine       arima           9.943284e+04    315.329724    11.448077
              mlpgs           1.278306e+05    354.185190    12.602391
              mlpkpssfalse    1.184225e+05    344.083135    12.021414
              mlpkpssfalsep1  1.408789e+05    375.004804    13.563179
              mlpkpssfalsep2  1.873571e+05    429.957228    15.105242
              mlpkpssfalsep3  2.815996e+05    514.569134    18.748423
              mlpwk0.61005    2.706427e+06   1430.898890    46.117616
              mlpwk11005      6.378359e+05    724.382113    23.658261
              svrgs           1.503653e+05    387.769675    14.914850
              svrwk0.6505     4.045150e+08  20112.557799   935.206639
sunspot       arima           4.609469e+02     21.469675    35.855626
              mlpgs           3.816033e+02     19.533637    32.131983
              mlpkpssfalse    5.616126e+02     23.616962    35.086902
              mlpkpssfalsep1  5.308623e+02     22.941398    33.224729
              mlpkpssfalsep2  5.406522e+02     23.121231    35.397181
              mlpkpssfalsep3  5.689191e+02     23.696678    40.299790
              mlpwk0.61005    6.439578e+02     24.974617    55.059293
              mlpwk0.81005    5.704501e+02     23.548431    42.446562
              mlpwk11005      5.563952e+02     23.462893    38.176999
              svrgs           5.189782e+02     22.781094    32.978979
              svrwk0.6505     8.446138e+03     91.902875   154.753533
temperature   arima           7.281369e+00      2.698401     4.576392
              mlpgs           5.164711e+00      2.270874     3.949504
              mlpkpssfalse    4.895748e+00      2.211426     3.850716
              mlpkpssfalsep1  5.575795e+00      2.360587     3.982828
              mlpkpssfalsep2  5.766053e+00      2.401084     4.059838
              mlpkpssfalsep3  5.686528e+00      2.381921     4.002292
              mlpwk0.61005    6.343725e+01      7.760375    12.732447
              mlpwk11005      2.116800e+01      4.307670     7.348280
              svrgs           6.339314e+00      2.517799     4.414923
woolyrnq      arima           1.956465e+05    442.319508     6.503041
              mlpgs           2.160807e+05    464.842712     7.078191
              mlpkpssfalse    1.845489e+05    429.565285     6.485474
              mlpkpssfalsep1  8.904330e+05    867.790925    12.631823
              mlpkpssfalsep2  4.025103e+06   1848.373421    31.151292
              mlpkpssfalsep3  5.432859e+06   2083.117842    35.290896
              mlpwk0.61005    1.175768e+07   2339.806925    41.318595
              mlpwk11005      2.614399e+05    510.022085     8.677586
              svrgs           2.379859e+05    487.837996     7.576133

                                       MAE          theil       ARV        IA  \
ts            model
Unemployment  arima              42.185424       0.459857  0.230224  0.937808
              mlpgs              27.124426       0.476039  0.129845  0.969584
              mlpkpssfalse       26.739629       0.431914  0.121791  0.971243
              mlpkpssfalsep1     25.555106       0.432005  0.123278  0.970987
              mlpkpssfalsep2     25.214391       0.391262  0.118062  0.972448
              mlpkpssfalsep3     26.903318       0.451947  0.137583  0.967947
              mlpwk0.61005       25.997885       0.473025  0.135786  0.968801
              mlpwk11005         25.205923       0.436020  0.124656  0.971014
              svrgs              33.372764       0.817258  0.253417  0.948664
              svrwk0.6505        35.307484       0.756327  0.244592  0.944703
ausbee        arima              10.380154       0.051159  0.102756  0.971924
              mlpgs              12.241128       0.063845  0.133218  0.961675
              mlpkpssfalse       11.830477       0.062444  0.128494  0.963353
              mlpkpssfalsep1     13.832712       0.071027  0.144371  0.956334
              mlpkpssfalsep2     14.309270       0.072708  0.147964  0.954786
              mlpkpssfalsep3     15.194784       0.077600  0.159124  0.951169
              mlpwk0.61005       69.711562       0.359641  0.607035  0.628826
              mlpwk11005         27.037195       0.168377  0.321721  0.868904
              svrgs              14.917657       0.082543  0.178280  0.947438
              svrwk0.6505      1224.149217     183.062999  1.002451  0.048363
austres       arima              13.114570       0.096512  0.004535  0.998868
              mlpgs              12.883760       0.106943  0.004937  0.998773
              mlpkpssfalse       39.947719       0.878120  0.034382  0.991496
              mlpkpssfalsep1     14.589914       0.098869  0.004730  0.998824
              mlpkpssfalsep2     14.893801       0.110836  0.005059  0.998747
              mlpkpssfalsep3     15.989719       0.126755  0.005795  0.998569
              mlpwk0.61005       14.926924       0.104494  0.004993  0.998760
              mlpwk11005         14.925224       0.104272  0.004993  0.998760
              svrgs              13.953330       0.114093  0.005239  0.998699
              svrwk0.6505     18030.381621  505707.452602  1.000213  0.024106
coloradoRiver arima               0.338786       0.733654  0.604486  0.820695
              mlpgs               0.271697       0.972648  0.738324  0.807383
              mlpkpssfalse        0.307493       1.289100  0.891461  0.792285
              mlpkpssfalsep1      0.292751       1.307984  0.846602  0.811122
              mlpkpssfalsep2      0.281583       1.212879  0.822787  0.817740
              mlpkpssfalsep3      0.287070       1.261004  0.800895  0.818936
              mlpwk0.61005        0.293695       0.965506  0.725045  0.822962
              mlpwk0.81005        0.305844       1.338589  0.842332  0.809052
              mlpwk11005          0.290212       1.267734  0.823716  0.817857
              svrgs               0.271063       1.464720  1.168036  0.748349
              svrwk0.6505        17.010237      45.496351  1.005886  0.031716
gasoline      arima             198.014828      17.416361  1.260852  0.746876
              mlpgs             195.972334      12.458338  1.294748  0.741379
              mlpkpssfalse      208.859979      19.580569  1.423240  0.718977
              mlpkpssfalsep1    211.289491      18.840413  1.455942  0.712336
              mlpkpssfalsep2    212.820328      18.083343  1.477555  0.707725
              mlpkpssfalsep3    213.346293      18.122146  1.497199  0.705301
              mlpwk0.61005      217.534340      19.251479  1.605770  0.689117
              mlpwk11005        219.485659      20.343954  1.612216  0.685462
              svrgs             196.863179       8.996561  1.282930  0.737683
heartrate     arima               0.524534       0.207036  0.013215  0.996657
              mlpgs               0.881269       0.755419  0.040514  0.990372
              mlpkpssfalse        0.752621       0.512587  0.028784  0.992971
              mlpkpssfalsep1      0.790795       0.582567  0.039895  0.990432
              mlpkpssfalsep2      0.755152       0.419979  0.034338  0.991237
              mlpkpssfalsep3      0.826155       0.637367  0.041103  0.990288
              mlpwk0.61005        1.638162       0.605839  0.162550  0.943919
              mlpwk11005          0.545277       0.245134  0.015524  0.996120
              svrgs               0.833926       0.758348  0.037978  0.990906
              svrwk0.6505         0.782485       0.550553  0.036058  0.990729
milk          arima               4.366052       0.029640  0.010097  0.997548
              mlpgs               4.504642       0.029191  0.009848  0.997569
              mlpkpssfalse        9.060388       0.143602  0.044183  0.989787
              mlpkpssfalsep1     11.393185       0.186203  0.072683  0.980585
              mlpkpssfalsep2     15.875976       0.269749  0.146070  0.956958
              mlpkpssfalsep3     19.471372       0.379000  0.195334  0.939371
              mlpwk0.61005       18.963737       0.265847  0.156520  0.954095
              mlpwk11005         10.978461       0.235947  0.087691  0.970664
              svrgs               4.455466       0.027886  0.009328  0.997704
              svrwk0.6505       223.023895       4.182082  1.101347  0.262436
ozon          arima               0.771584       0.765322  0.203351  0.950337
              mlpgs               0.806273       0.490649  0.230580  0.940433
              mlpkpssfalse        0.816185       0.610658  0.244331  0.938442
              mlpkpssfalsep1      0.787919       0.617408  0.224039  0.943534
              mlpkpssfalsep2      0.795489       0.596132  0.224889  0.941542
              mlpkpssfalsep3      1.069897       0.562324  0.304602  0.909268
              mlpwk0.61005        0.773533       0.602213  0.215760  0.944431
              mlpwk11005          0.779367       0.588939  0.213886  0.945640
              svrgs               0.668507       0.487718  0.163333  0.958244
              svrwk0.6505         3.882316       0.486280  1.087132  0.379606
pollution     arima             678.434732       1.194800  1.667647  0.650432
              mlpgs             601.534128       0.325071  0.692431  0.807602
              mlpkpssfalse      548.673500       0.435645  0.912065  0.793619
              mlpkpssfalsep1    728.885268       1.020254  1.530238  0.641081
              mlpkpssfalsep2    814.699211       0.770543  1.192763  0.647042
              mlpkpssfalsep3    657.505476       0.680706  1.186833  0.718017
              mlpwk0.61005      591.695414       0.790025  1.321690  0.741513
              mlpwk11005        659.280037       0.905746  1.446384  0.687797
              svrgs             543.415889       0.413079  0.738169  0.816417
              svrwk0.6505      2052.092217       0.795194  0.976372  0.388610
redwine       arima             245.755306       0.424564  0.417392  0.919119
              mlpgs             261.895444       0.342812  0.372308  0.910720
              mlpkpssfalse      265.607835       0.393850  0.423476  0.909409
              mlpkpssfalsep1    291.952896       0.677045  0.704088  0.874092
              mlpkpssfalsep2    339.558522       1.038062  0.892819  0.832395
              mlpkpssfalsep3    403.281640       0.562610  0.638188  0.818815
              mlpwk0.61005     1079.278735       1.449866  1.463617  0.331942
              mlpwk11005        553.170407       2.202362  1.750835  0.597742
              svrgs             299.543436       0.420183  0.469917  0.890208
              svrwk0.6505     20104.361013    4377.430020  1.000619  0.045365
sunspot       arima              16.025658       0.362792  0.189991  0.953298
              mlpgs              14.290059       0.360281  0.169564  0.959987
              mlpkpssfalse       17.336785       0.603807  0.290507  0.935636
              mlpkpssfalsep1     16.726061       0.570016  0.267957  0.939883
              mlpkpssfalsep2     17.178728       0.520167  0.260308  0.940024
              mlpkpssfalsep3     17.907391       0.535994  0.265054  0.937802
              mlpwk0.61005       19.480554       0.440715  0.268405  0.932862
              mlpwk0.81005       17.609911       0.493170  0.257698  0.938631
              mlpwk11005         17.298155       0.523059  0.262374  0.938895
              svrgs              16.647222       0.603114  0.265826  0.941508
              svrwk0.6505        64.355146       0.364459  0.724337  0.631315
temperature   arima               2.100623       0.343320  0.105814  0.973069
              mlpgs               1.816165       0.256302  0.076074  0.980884
              mlpkpssfalse        1.766437       0.248135  0.072038  0.981902
              mlpkpssfalsep1      1.820376       0.242928  0.078626  0.979796
              mlpkpssfalsep2      1.881690       0.242929  0.081676  0.979051
              mlpkpssfalsep3      1.854325       0.241832  0.081119  0.979270
              mlpwk0.61005        6.226101       0.383094  0.398890  0.843938
              mlpwk11005          3.511815       0.307567  0.194166  0.937579
              svrgs               2.043596       0.301368  0.095297  0.976204
woolyrnq      arima             311.281048       0.484294  0.642411  0.840014
              mlpgs             342.086861       0.376432  0.564641  0.841132
              mlpkpssfalse      311.400249       0.348247  0.511902  0.861906
              mlpkpssfalsep1    592.247032       0.455174  0.885918  0.623016
              mlpkpssfalsep2   1443.830901       0.742623  1.006988  0.350836
              mlpkpssfalsep3   1678.587764       0.987032  0.924374  0.388918
              mlpwk0.61005     1960.408150       1.923442  0.913881  0.424765
              mlpwk11005        407.797738       0.373342  0.639229  0.806741
              svrgs             362.447544       0.402619  0.624154  0.820683

                                  POCID    val_metric  time_testing  \
ts            model
Unemployment  arima           64.583333           inf           inf
              mlpgs           75.833333  2.819967e+01      0.000350
              mlpkpssfalse    76.875000  2.823149e+01      0.000254
              mlpkpssfalsep1  75.833333  2.432464e+01           inf
              mlpkpssfalsep2  75.625000  2.454871e+01           inf
              mlpkpssfalsep3  76.041667  3.152635e+01           inf
              mlpwk0.61005    75.833333  2.427857e+01           inf
              mlpwk11005      75.625000  2.420517e+01           inf
              svrgs           77.083333  3.280620e+01      0.001944

In [87]:
metric = 'RMSE'
df_arima = pd.DataFrame()
df_svr = pd.DataFrame()
df_mlp = pd.DataFrame()

proposed_list = []
for k, df in df_mean_metrics.reset_index().groupby('ts'):
    arima = df[df['model'] == 'arima'][metric].iloc[0]
    svr = df[df['model'] == 'arima'][metric].iloc[0]
    mlp = df[df['model'] == 'arima'][metric].iloc[0]

    df_arima[k] = (df.set_index('model')[metric] < arima)
    df_svr[k] = (df.set_index('model')[metric] < svr)
    df_mlp[k] = (df.set_index('model')[metric] < mlp)

    svr_proposed = df[( (df['model'].str.contains("svr-")) & (df['model'].str.contains("-1")))].copy()
    if svr_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(svr_proposed.iloc[svr_proposed['val_metric'].argmin()]).T)

    mlp_proposed = df[( (df['model'].str.contains("mlp-")) )].copy()
    if mlp_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(mlp_proposed.iloc[mlp_proposed['val_metric'].argmin()]).T)

    proposed_list.append(
        df[df['model'].isin(
            ['arima', 'arimamlp', 'arimasvr', 'mlpgs', 'svrgs']
        )]
    )

In [297]:
pd.concat(proposed_list)

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
13,Unemployment,mlp-5-0.5,1537.350999,39.197924,5.04158,29.994161,0.323482,0.130086,0.966939,71.041667,30.410345,0.001313,0.258301
0,Unemployment,arima,2978.55064,54.5761,7.012015,42.185424,0.459857,0.230224,0.937808,64.583333,inf,inf,inf
1,Unemployment,arimamlp,1507.623215,38.015974,4.99482,29.138739,0.255764,0.119458,0.968734,68.75,29.110805,0.000266,1.12956
2,Unemployment,arimasvr,1275.651599,35.716265,4.628084,26.542111,0.255639,0.111756,0.972213,70.833333,29.210214,0.001345,0.012543
15,Unemployment,mlpgs,1257.368291,35.450172,4.457729,26.569295,0.446288,0.120187,0.971427,75.625,28.047807,0.000295,0.104141
16,Unemployment,svrgs,1935.252226,43.991502,5.36371,33.372764,0.817258,0.253417,0.948664,77.083333,32.806197,0.001205,0.008954
29,ausbee,mlp-5-0.1,187.663518,13.698986,2.467034,10.466893,0.051816,0.103955,0.971565,95.238095,16.825221,0.001105,0.017484
17,ausbee,arima,185.170053,13.60772,2.445095,10.380154,0.051159,0.102756,0.971924,95.238095,inf,inf,inf
18,ausbee,arimamlp,206.236338,14.355229,2.596583,11.002181,0.056505,0.112594,0.968929,95.238095,17.761218,0.00024,0.071745
19,ausbee,arimasvr,197.724956,14.061471,2.573711,10.889252,0.054385,0.109454,0.970015,95.238095,17.185626,0.000352,0.001207
32,ausbee,mlpgs,265.946752,16.298976,2.882458,12.259968,0.065541,0.136945,0.960894,95.0,19.01511,0.000233,0.078886
33,ausbee,svrgs,363.558586,19.067212,3.483389,14.917657,0.082543,0.17828,0.947438,92.857143,19.873014,0.000408,0.002005
46,austres,mlp-5-0.1,342.159309,18.493436,0.08857,15.31258,0.115082,0.005309,0.998676,94.117647,16.899684,0.000953,0.077955
34,austres,arima,292.529006,17.103479,0.075877,13.11457,0.096512,0.004535,0.998868,94.117647,inf,inf,inf
35,austres,arimamlp,293.189489,17.11932,0.07583,13.105325,0.097224,0.004547,0.998866,94.117647,7.097076,0.000569,0.005992
36,austres,arimasvr,280.965321,16.76202,0.079991,13.834553,0.096503,0.004374,0.998911,94.117647,23.06793,0.000279,0.001055
49,austres,mlpgs,319.075549,17.862043,0.075524,13.051408,0.108204,0.004991,0.99876,88.235294,8.919154,0.000268,0.094925
50,austres,svrgs,334.805911,18.297702,0.080785,13.95333,0.114093,0.005239,0.998699,94.117647,9.211441,0.000408,0.001978
63,coloradoRiver,mlp-5-0.1,0.276248,0.525592,93.774663,0.338144,0.734588,0.603246,0.821163,62.567568,0.63525,0.001064,0.052956
51,coloradoRiver,arima,0.276939,0.52625,93.935436,0.338786,0.733654,0.604486,0.820695,62.162162,inf,inf,inf
52,coloradoRiver,arimamlp,0.278126,0.527368,93.407738,0.339457,0.737819,0.607008,0.819936,61.891892,0.645575,0.00029,0.153007
53,coloradoRiver,arimasvr,0.288012,0.536668,97.670336,0.345611,0.843487,0.682757,0.803673,59.459459,0.670363,0.007594,0.04723
66,coloradoRiver,mlpgs,0.243663,0.493413,74.509901,0.26536,0.985498,0.745235,0.808425,63.378378,0.792289,0.000309,0.096385
67,coloradoRiver,svrgs,0.263999,0.513808,68.067915,0.271063,1.46472,1.168036,0.748349,66.216216,0.746652,0.004055,0.529079
81,gasoline,mlp-5-0.5,60435.519094,245.83036,2.213503,197.539627,16.941539,1.257739,0.744913,36.845638,314.261537,0.001253,0.017277
68,gasoline,arima,59642.241667,244.217611,2.21646,198.014828,17.416361,1.260852,0.746876,35.57047,inf,inf,inf
69,gasoline,arimamlp,60072.37927,245.09315,2.21084,197.241502,14.656421,1.254871,0.746224,36.979866,315.41656,0.000408,0.027855
70,gasoline,arimasvr,59464.621812,243.853689,2.156669,192.360451,10.882333,1.291334,0.747024,40.939597,316.791634,0.010174,0.044097
83,gasoline,mlpgs,61108.436831,247.20051,2.194006,195.868236,13.02937,1.287565,0.742271,40.536913,315.988534,0.000262,0.109604
84,gasoline,svrgs,63408.220492,251.80989,2.203433,196.863179,8.996561,1.28293,0.737683,40.939597,321.047474,0.010909,0.062229
90,heartrate,mlp-10-1,0.439619,0.662943,0.61534,0.543635,0.21975,0.01421,0.996396,57.0,0.538357,0.002412,0.028776
85,heartrate,arima,0.406941,0.63792,0.594484,0.524534,0.207036,0.013215,0.996657,56.666667,inf,inf,inf
86,heartrate,arimamlp,0.446085,0.667868,0.618227,0.546185,0.22437,0.014453,0.996338,57.0,0.539496,0.001704,0.008179
87,heartrate,arimasvr,0.548302,0.740474,0.671466,0.589953,0.285608,0.018108,0.995452,60.0,0.543197,0.000304,0.001081
100,heartrate,mlpgs,5.276087,1.719428,1.536108,1.309642,2.463187,0.094499,0.970062,54.666667,0.663002,0.000231,0.104732
101,heartrate,svrgs,1.038407,1.019023,0.961778,0.833926,0.758348,0.037978,0.990906,53.333333,0.671926,0.00061,0.009868
114,milk,mlp-5-0.1,32.245895,5.678513,0.521745,4.369729,0.029692,0.010116,0.997544,96.774194,6.920522,0.00095,0.044403
102,milk,arima,32.188552,5.673496,0.521295,4.366052,0.02964,0.010097,0.997548,96.774194,inf,inf,inf
103,milk,arimamlp,32.517942,5.6995,0.521125,4.363018,0.029895,0.0102,0.997523,96.451613,6.95786,0.000247,0.082176
104,milk,arimasvr,30.520686,5.524553,0.502387,4.21559,0.028019,0.009558,0.997677,96.774194,7.240846,0.000386,0.001516
117,milk,mlpgs,31.759966,5.633236,0.538672,4.502022,0.028522,0.009678,0.997615,95.483871,7.462193,0.000238,0.108072
118,milk,svrgs,30.551798,5.527368,0.530865,4.455466,0.027886,0.009328,0.997704,93.548387,8.022814,0.00068,0.003003
128,ozon,mlp-40-0.1,0.811065,0.900591,16.79861,0.733009,0.687014,0.196962,0.951381,86.111111,1.014117,0.009918,0.780964
119,ozon,arima,0.8166,0.903659,17.818441,0.771584,0.765322,0.203351,0.950337,77.777778,inf,inf,inf
120,ozon,arimamlp,0.952416,0.9759,19.232768,0.794835,0.584003,0.215147,0.94463,80.833333,1.043837,0.000226,0.171751
121,ozon,arimasvr,0.962097,0.980865,18.397815,0.779863,0.572309,0.214182,0.944475,77.777778,1.018892,0.002979,0.006791
134,ozon,mlpgs,1.032398,1.01598,19.260219,0.815901,0.611495,0.245411,0.938166,71.944444,1.117066,0.000259,0.085851
135,ozon,svrgs,0.729022,0.853828,15.862582,0.668507,0.487718,0.163333,0.958244,77.777778,1.08088,0.000579,0.003344
139,pollution,mlp-10-0.1,633681.315648,794.840701,21.951843,648.155216,0.974033,1.315813,0.704911,74.230769,479.411208,0.002285,0.784825
136,pollution,arima,673964.331798,820.953307,23.080686,678.434732,1.1948,1.667647,0.650432,76.923077,inf,inf,inf
137,pollution,arimamlp,564639.4568,751.382885,21.107666,658.8197,0.290426,0.575792,0.820679,76.923077,490.706124,0.00025,0.505283
138,pollution,arimasvr,497142.345584,705.083219,18.068183,542.194919,0.449428,0.845464,0.791269,76.923077,441.60686,0.000629,0.002888
151,pollution,mlpgs,533977.179804,730.590184,20.899496,603.714678,0.322431,0.683003,0.809201,71.538462,429.435955,0.00033,0.105044
152,pollution,svrgs,468401.484845,684.39863,18.847271,543.415889,0.413079,0.738169,0.816417,73.076923,427.0412,0.000543,0.002427
165,redwine,mlp-5-0.1,98456.798506,313.778169,11.330787,243.433711,0.410176,0.411378,0.920091,75.405405,190.608267,0.001066,0.121295
153,redwine,arima,99432.83505,315.329724,11.448077,245.755306,0.424564,0.417392,0.919119,75.675676,inf,inf,inf
154,redwine,arimamlp,98944.901705,314.554028,11.31025,244.520052,0.357357,0.392063,0.921331,72.702703,225.134921,0.000324,0.145479
155,redwine,arimasvr,109980.170984,331.632584,11.44232,256.81571,0.429978,0.476544,0.908745,70.27027,201.662198,0.002365,0.003581
168,redwine,mlpgs,131905.338326,361.652914,12.924504,274.703529,0.310267,0.367518,0.909767,65.405405,263.132514,0.000276,0.233274
169,redwine,svrgs,150365.320651,387.769675,14.91485,299.543436,0.420183,0.469917,0.890208,56.756757,233.021622,0.000914,0.005031
182,sunspot,mlp-5-0.1,437.633375,20.919447,35.16927,15.522309,0.357629,0.185832,0.955027,75.789474,12.008234,0.001025,0.212399
170,sunspot,arima,460.946929,21.469675,35.855626,16.025658,0.362792,0.189991,0.953298,73.684211,inf,inf,inf
171,sunspot,arimamlp,383.90361,19.59328,31.669947,14.446748,0.299652,0.157737,0.961153,75.789474,14.353232,0.002198,1.49869
172,sunspot,arimasvr,560.834914,23.681953,32.428406,17.269608,0.330496,0.213946,0.944649,77.192982,14.245111,0.002789,0.034623
185,sunspot,mlpgs,397.872857,19.93946,32.199995,14.598512,0.375703,0.181319,0.957729,81.052632,13.62129,0.000374,1.193554
186,sunspot,svrgs,518.978223,22.781094,32.978979,16.647222,0.603114,0.265826,0.941508,84.210526,12.149624,0.001634,0.01089
187,taylor,arima,161228.574554,401.532781,0.986927,285.137964,0.136111,0.005593,0.998604,79.528536,inf,inf,inf
188,taylor,arimamlp,171213.840471,413.228576,1.013953,293.48347,0.143036,0.005891,0.998523,79.280397,385.079529,0.000331,0.195804
189,taylor,arimasvr,123165.234717,350.949049,0.87249,249.85301,0.11492,0.004268,0.998934,81.637717,333.629548,0.087631,3.778042
199,temperature,mlp-40-0.1,6.290009,2.507847,4.308185,1.977324,0.302328,0.093892,0.976495,76.875,2.658588,0.008608,4.086537
190,temperature,arima,7.281369,2.698401,4.576392,2.100623,0.34332,0.105814,0.973069,75.0,inf,inf,inf
191,temperature,arimamlp,5.971973,2.443719,4.238518,1.932254,0.286678,0.090385,0.977544,75.208333,2.722754,0.000336,0.729989
192,temperature,arimasvr,6.944703,2.635281,4.470903,2.080581,0.275801,0.101807,0.974221,75.0,2.726609,0.002846,0.019655
205,temperature,mlpgs,5.341964,2.30646,4.030272,1.853695,0.262871,0.079089,0.980162,75.416667,2.613023,0.000233,0.08597
206,temperature,svrgs,6.339314,2.517799,4.414923,2.043596,0.301368,0.095297,0.976204,70.833333,2.546292,0.00057,0.005583
219,woolyrnq,mlp-5-0.1,178855.292964,422.911942,6.362992,303.897179,0.371077,0.548658,0.858955,78.26087,326.855658,0.001358,0.018618
207,woolyrnq,arima,178336.664832,422.29926,6.347699,303.050622,0.370373,0.547525,0.859332,78.26087,inf,inf,inf
208,woolyrnq,arimamlp,184768.276672,429.657079,6.518435,311.999599,0.376899,0.5587,0.855062,79.130435,347.958207,0.001507,0.013269
209,woolyrnq,arimasvr,227350.669875,476.813035,7.510956,361.352648,0.412043,0.678778,0.819508,73.913043,363.775367,0.000499,0.002073
222,woolyrnq,mlpgs,217577.187554,466.446893,7.12815,344.260691,0.374522,0.563249,0.840827,82.608696,413.243336,0.00027,0.083267
223,woolyrnq,svrgs,237985.909935,487.837996,7.576133,362.447544,0.402619,0.624154,0.820683,73.913043,316.54427,0.000521,0.002933

ts                    woolyrnq
model              svr-10-0.01
MSE              179419.653158
RMSE                423.579571
MAPE                  6.355562
MAE                  303.52592
theil                  0.37125
ARV                   0.551535
IA                    0.858312
POCID                 78.26087
val_metric          322.010763
time_testing          0.004785
time_training         0.109223
Name: 118, dtype: object

In [276]:
df_mean_metrics.reset_index()['ts'].nunique()

14

In [277]:
df_arima.sum(axis=1)

model
arima           0
arimamlp        5
arimasvr        7
mlp-1-0.01     10
mlp-1-0.1      10
mlp-1-0.5       6
mlp-1-1         4
mlp-10-0.01     9
mlp-10-0.1      9
mlp-10-0.5      5
mlp-10-1        5
mlp-2-0.01      9
mlp-2-0.1       8
mlp-2-0.5       5
mlp-2-1         3
mlp-20-0.01     9
mlp-20-0.1      9
mlp-20-0.5      5
mlp-20-1        5
mlp-3-0.01      9
mlp-3-0.1       7
mlp-3-0.5       5
mlp-3-1         6
mlp-40-0.01     9
mlp-40-0.1      7
mlp-40-0.5      5
mlp-40-1        5
mlp-5-0.01      8
mlp-5-0.1       7
mlp-5-0.5       7
mlp-5-1         5
mlpgs           6
svrgs           6
dtype: object

In [122]:
df_mlp.sum(axis=1)

model
arima               8
arimamlp            9
arimasvr            9
lrcmlp-15-0.01      7
lrcmlp-15-0.1       8
lrcmlp-15-0.5       7
lrcmlp-15-1         7
lrcmlp-3-0.01       7
lrcmlp-3-0.1        7
lrcmlp-3-0.5        7
lrcmlp-3-1          5
lrcmlp-30-0.01      7
lrcmlp-30-0.1       8
lrcmlp-30-0.5       5
lrcmlp-30-1         5
lrcmlp-5-0.01       7
lrcmlp-5-0.1        6
lrcmlp-5-0.5        7
lrcmlp-5-1          6
lrcmlp-60-0.01      6
lrcmlp-60-0.1       7
lrcmlp-60-0.5       6
lrcmlp-60-1         5
lrcmlpinv-10-0.9    8
lrcmlpinv-2-0.9     8
lrcmlpinv-20-0.9    7
lrcmlpinv-4-0.9     8
lrcmlpinv-6-0.9     7
lrcmlpinv-8-0.9     7
lrcsvr-15-0.01      7
lrcsvr-15-0.1       7
lrcsvr-15-0.5       3
lrcsvr-15-1         3
lrcsvr-2-0.9        6
lrcsvr-3-0.01       7
lrcsvr-3-0.1        7
lrcsvr-3-0.5        7
lrcsvr-3-1          6
lrcsvr-30-0.01      7
lrcsvr-30-0.1       5
lrcsvr-30-0.5       2
lrcsvr-30-1         2
lrcsvr-4-0.9        7
lrcsvr-5-0.01       7
lrcsvr-5-0.1        6
lrcsvr-5-0.5        6
lrcsvr-5-1          5
lrcsvr-6-0.9        7
lrcsvr-60-0.01      6
lrcsvr-60-0.1       4
lrcsvr-60-0.5       2
lrcsvr-60-1         2
lrcsvr-8-0.9        6
mlpgs               0
svrgs               5
dtype: object

In [123]:
df_svr.sum(axis=1)

model
arima                8
arimamlp            10
arimasvr             9
lrcmlp-15-0.01       7
lrcmlp-15-0.1        8
lrcmlp-15-0.5        7
lrcmlp-15-1          7
lrcmlp-3-0.01        7
lrcmlp-3-0.1         6
lrcmlp-3-0.5         7
lrcmlp-3-1           5
lrcmlp-30-0.01       6
lrcmlp-30-0.1        7
lrcmlp-30-0.5        7
lrcmlp-30-1          5
lrcmlp-5-0.01        7
lrcmlp-5-0.1         7
lrcmlp-5-0.5         7
lrcmlp-5-1           7
lrcmlp-60-0.01       8
lrcmlp-60-0.1        8
lrcmlp-60-0.5        6
lrcmlp-60-1          5
lrcmlpinv-10-0.9     7
lrcmlpinv-2-0.9      8
lrcmlpinv-20-0.9     7
lrcmlpinv-4-0.9      8
lrcmlpinv-6-0.9      7
lrcmlpinv-8-0.9      6
lrcsvr-15-0.01       7
lrcsvr-15-0.1        7
lrcsvr-15-0.5        5
lrcsvr-15-1          5
lrcsvr-2-0.9         6
lrcsvr-3-0.01        7
lrcsvr-3-0.1         7
lrcsvr-3-0.5         6
lrcsvr-3-1           6
lrcsvr-30-0.01       7
lrcsvr-30-0.1        6
lrcsvr-30-0.5        4
lrcsvr-30-1          4
lrcsvr-4-0.9         6
lrcsvr-5-0.01        7
lrcsvr-5-0.1         8
lrcsvr-5-0.5         6
lrcsvr-5-1           6
lrcsvr-6-0.9         6
lrcsvr-60-0.01       8
lrcsvr-60-0.1        6
lrcsvr-60-0.5        4
lrcsvr-60-1          3
lrcsvr-8-0.9         6
mlpgs                9
svrgs                0
dtype: object