In [1]:
import pandas as pd
import matplotlib as plt
from metrics import metrics
from model import generics
pd.set_option('display.max_rows', 2000)

%load_ext autoreload
%autoreload 2

In [2]:
experiment_id = 'resudualens'

In [5]:
df_mean_metrics, df_all_metrics, df_prevs = metrics.open_fold_result(experiment_id)

In [6]:
df_mean_metrics.reset_index().sort_values(by=['ts', 'model'])#[df_mean_metrics.reset_index()['model'].str.contains("mlp-").values]
#usadas no artigo Airlines River Lake Milk Ozone Paper PollutionStar Sunspot Temperature

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
0,Unemployment,1am,1.355860e+03,36.821928,4.443740,27.018404,0.315899,0.090815,0.977188,70.833333,25.701975,0.000218,0.088543
1,Unemployment,1amens,1.474900e+03,38.398665,4.570841,28.065911,0.304059,0.101756,0.974818,72.916667,27.898328,0.045145,1.416373
2,Unemployment,1arima,3.367940e+03,58.033959,6.515261,42.026475,0.471769,0.210969,0.943804,70.833333,inf,inf,inf
3,Unemployment,1as,1.322241e+03,36.362637,4.599497,28.307749,0.285973,0.089732,0.977632,66.666667,26.402280,0.000256,0.001933
4,Unemployment,1asens,1.643765e+03,40.529123,4.862633,29.981828,0.326211,0.115321,0.971645,69.166667,29.002039,0.033951,0.115142
5,Unemployment,1elm,1.195962e+03,34.578168,4.220603,25.797267,0.272980,0.081514,0.979738,65.416667,25.507882,0.000091,0.013658
6,Unemployment,1mlp,1.227733e+03,35.038242,4.194633,25.868907,0.285525,0.084710,0.979055,63.750000,25.933508,0.000297,0.288898
7,Unemployment,1svr,1.056385e+03,32.502073,4.101036,24.105751,0.238184,0.074374,0.981888,66.666667,22.476597,0.000589,0.015608
8,ausbee,1am,2.571279e+02,16.033896,2.685414,11.187198,0.094734,0.176233,0.947829,95.238095,14.894268,0.000199,0.053449
9,ausbee,1amens,2.723986e+02,16.504256,3.085836,12.912529,0.109772,0.206894,0.941220,95.238095,14.481460,0.042338,0.122985
10,ausbee,1arima,2.751478e+02,16.587580,3.128794,13.102531,0.111015,0.210175,0.940390,95.238095,inf,inf,inf
11,ausbee,1as,2.841879e+02,16.857873,2.857842,11.813287,0.102074,0.188851,0.943145,95.238095,14.745258,0.000314,0.001640
12,ausbee,1asens,2.653443e+02,16.289231,3.084943,12.927774,0.106088,0.201373,0.942806,95.238095,14.383242,0.040085,0.057557
13,ausbee,1elm,2.460521e+02,15.682530,2.829254,11.873042,0.083119,0.160410,0.951537,95.238095,15.827530,0.000101,0.018074
14,ausbee,1mlp,2.565738e+02,16.014606,2.624605,11.001652,0.084952,0.169981,0.948854,95.238095,15.473586,0.000267,0.348765
15,ausbee,1svr,3.359869e+02,18.329944,3.422244,14.468123,0.104916,0.204601,0.935664,95.238095,15.155091,0.000617,0.016603
16,austres,1am,2.943825e+03,54.256461,0.290670,50.903803,1.191499,0.236479,0.929875,87.500000,52.059218,0.000197,0.015733
17,austres,1amens,5.760758e+02,23.777294,0.121836,21.309949,0.219246,0.055502,0.985557,75.000000,20.544275,0.037484,0.122908
18,austres,1arima,3.581316e+02,18.924365,0.078380,13.710330,0.129713,0.034904,0.990999,75.000000,inf,inf,inf
19,austres,1as,3.832384e+02,19.576477,0.090181,15.761930,0.149014,0.038063,0.990280,87.500000,17.359958,0.000174,0.000453
20,austres,1asens,3.558086e+02,18.862801,0.081626,14.267643,0.134065,0.035070,0.991012,75.000000,16.675508,0.043428,0.065000
21,austres,1elm,3.302518e+02,18.078528,0.076234,13.336019,0.132551,0.034072,0.991466,80.000000,17.368624,0.000076,0.012021
22,austres,1mlp,3.984211e+02,19.957359,0.083277,14.567205,0.154979,0.042526,0.989517,75.000000,16.861987,0.000237,0.336752
23,austres,1svr,3.581322e+02,18.924382,0.080876,14.142564,0.145121,0.037690,0.990642,87.500000,16.838591,0.000377,0.001549
24,coloradoRiver,1am,1.054103e-01,0.324668,28.735633,0.263108,0.734753,0.697479,0.670043,55.540541,0.677055,0.000237,0.376771
25,coloradoRiver,1amens,1.052287e-01,0.324366,28.704405,0.262895,0.735720,0.699133,0.669171,55.675676,0.679721,0.044499,0.161231
26,coloradoRiver,1arima,1.067550e-01,0.326734,29.063906,0.266386,0.750629,0.697794,0.666893,51.351351,inf,inf,inf
27,coloradoRiver,1as,1.157236e-01,0.340182,31.208702,0.281705,0.769452,0.672576,0.669733,66.216216,0.690284,0.000518,0.006001
28,coloradoRiver,1asens,1.155766e-01,0.339938,31.092221,0.282133,0.814558,0.684785,0.665591,61.621622,0.683395,0.031711,0.101847
29,coloradoRiver,1elm,1.956297e-02,0.139332,14.552774,0.112234,0.843732,0.571025,0.864863,70.135135,0.689594,0.000111,0.020545
30,coloradoRiver,1mlp,1.880838e-02,0.137120,13.533104,0.108969,0.783376,0.607355,0.865842,61.351351,0.668893,0.000288,0.995700
31,coloradoRiver,1svr,1.673503e-02,0.129364,12.780709,0.103989,0.990695,0.654656,0.870977,70.270270,0.674405,0.001814,0.032213
32,gasoline,1am,4.149845e+04,203.708827,1.808960,162.747992,11.179156,1.182677,0.758772,44.189189,281.914516,0.000193,0.140035
33,gasoline,1amens,4.011005e+04,200.274879,1.799248,161.859198,15.656592,1.145377,0.767512,42.837838,282.690594,0.038630,0.113560
34,gasoline,1arima,4.024233e+04,200.604918,1.818217,163.787390,15.868613,1.149002,0.765986,43.243243,inf,inf,inf
35,gasoline,1as,4.075844e+04,201.887200,1.779735,160.070815,9.542606,1.234185,0.758475,41.891892,279.941234,0.001706,0.013284
36,gasoline,1asens,4.039525e+04,200.985286,1.793751,161.345428,15.032615,1.207525,0.761373,43.783784,281.756485,0.040336,0.106698
37,gasoline,1elm,4.199136e+04,204.908231,1.802030,162.213932,10.200216,1.138493,0.761557,44.054054,287.393822,0.000100,0.033174
38,gasoline,1mlp,4.268297e+04,206.591050,1.837497,165.501453,11.929085,1.192626,0.752627,43.648649,282.026514,0.000253,1.440022
39,gasoline,1svr,4.596904e+04,214.403916,1.889711,170.366131,8.641945,1.304089,0.731922,43.243243,284.499112,0.001248,0.300313
40,heartrate,1am,2.912499e-01,0.539675,0.545900,0.458011,0.328852,0.113878,0.967038,26.666667,0.762095,0.000205,0.052710
41,heartrate,1amens,3.026101e-01,0.550090,0.569159,0.477384,0.315409,0.116855,0.965955,26.666667,0.763791,0.036070,0.113557
42,heartrate,1arima,2.662160e-01,0.515961,0.555209,0.465495,0.277636,0.104168,0.969943,26.666667,inf,inf,inf
43,heartrate,1as,2.590205e-01,0.508941,0.571822,0.479014,0.242920,0.101500,0.970755,26.666667,0.741076,0.000247,0.001066
44,heartrate,1asens,2.628328e-01,0.512613,0.563065,0.471732,0.259076,0.103905,0.970162,26.666667,0.729999,0.024997,0.103449
45,heartrate,1elm,3.435015e-01,0.586073,0.485180,0.407285,0.739770,0.112066,0.964952,30.666667,1.033252,0.000080,0.003812
46,heartrate,1mlp,7.581384e-01,0.860319,0.909621,0.759088,1.754186,0.322789,0.904986,33.333333,1.019432,0.000204,0.166745
47,heartrate,1svr,6.553573e+00,2.559995,2.819059,2.339560,33.278475,1.133331,0.535772,26.666667,1.010793,0.000535,0.020482
48,irradiancefloripa,1elm,2.452251e+05,495.180202,120.275710,357.130164,0.550945,0.199745,0.951284,71.073684,519.241627,0.010728,0.546185
49,irradiancefloripa,1mlp,2.583489e+05,508.271191,131.448890,365.980097,0.552358,0.193627,0.950708,71.578947,532.532531,0.000370,0.548997
50,irradiancefloripa,1svr,2.381931e+05,488.050315,104.246962,336.337601,0.537605,0.190657,0.953201,72.000000,510.216998,0.126248,3.435419
51,irradiancefortaleza,1elm,5.308708e+04,230.397677,60.967650,165.520527,0.235261,0.066403,0.983711,85.263158,248.622447,0.007931,0.365636
52,irradiancefortaleza,1mlp,5.797180e+04,240.671153,53.050544,173.309283,0.251561,0.071658,0.982288,85.431579,254.647654,0.003816,0.964782
53,irradiancefortaleza,1svr,4.954906e+04,222.596176,46.658491,155.490482,0.219199,0.061224,0.984903,85.052632,237.965153,0.075294,0.867297
54,irradiancesalvador,1arima,3.650886e+05,604.225592,92.884777,462.077816,0.507060,0.194226,0.945134,76.421053,inf,inf,inf
55,irradiancesalvador,1elm,2.161459e+05,464.903372,48.112610,323.328387,0.465114,0.147567,0.963696,80.084211,496.056366,0.010037,0.310762
56,irradiancesalvador,1mlp,2.364399e+05,486.184208,55.743008,338.440892,0.495789,0.160092,0.960341,79.578947,517.803733,0.009331,1.101757
57,irradiancesalvador,1svr,2.126216e+05,461.109132,34.823105,301.679435,0.429404,0.138999,0.965113,80.631579,481.924745,0.247920,5.975839
58,irradiancesp,1elm,8.700321e+05,932.708460,inf,619.009917,1.415741,0.916410,0.802224,63.747368,966.479309,0.007584,0.473792
59,irradiancesp,1mlp,8.217727e+05,906.332805,inf,604.236707,1.601730,0.903217,0.809045,65.410526,959.601400,0.000413,3.857172
60,irradiancesp,1svr,8.069300e+05,898.292839,inf,580.027933,1.234920,0.810297,0.821906,66.315789,948.943833,0.027569,0.383906
61,melbmin,1am,5.137975e+00,2.266710,18.158844,1.743900,2.162593,0.528854,0.886435,43.835616,2.145489,0.000355,0.613982
62,melbmin,1amens,5.127682e+00,2.264438,18.139816,1.741642,2.152170,0.526956,0.886769,43.917808,2.146489,0.051792,0.254485
63,melbmin,1arima,5.104820e+00,2.259385,18.168100,1.739152,2.134016,0.523000,0.887529,43.835616,inf,inf,inf
64,melbmin,1as,5.180884e+00,2.276156,18.235516,1.751092,2.116245,0.533627,0.885303,42.739726,2.128627,0.014369,0.146498
65,melbmin,1asens,5.233691e+00,2.287724,18.319495,1.753294,2.125835,0.538067,0.884270,43.534247,2.126723,0.189045,10.359528
66,melbmin,1elm,5.193246e+00,2.278841,18.334439,1.757454,2.145996,0.542312,0.884414,43.315068,2.159628,0.010051,0.366253
67,melbmin,1mlp,5.205255e+00,2.281460,18.288136,1.753201,2.540015,0.555925,0.882964,44.191781,2.153468,0.007204,1.148190
68,melbmin,1svr,5.076043e+00,2.253008,17.958814,1.741966,2.121064,0.498284,0.890223,43.287671,2.146753,0.013100,0.131098
69,milk,1am,2.150476e+01,4.527524,0.426904,3.551866,0.024910,0.006349,0.998481,93.333333,7.339537,0.000215,0.106153
70,milk,1amens,1.843703e+01,4.293746,0.397631,3.330817,0.021438,0.005309,0.998713,93.333333,6.820369,0.044593,0.120738
71,milk,1arima,1.834033e+01,4.282561,0.395625,3.315280,0.021327,0.005282,0.998720,93.333333,inf,inf,inf
72,milk,1as,1.980900e+01,4.450730,0.409336,3.387781,0.022419,0.005513,0.998641,93.333333,6.084470,0.000278,0.003551
73,milk,1asens,2.077999e+01,4.557273,0.406763,3.378924,0.023984,0.005886,0.998561,93.333333,6.264871,0.034873,0.094055
74,milk,1elm,4.610068e+01,6.729477,0.626780,5.277785,0.055137,0.013208,0.996784,93.333333,6.727448,0.000085,0.012250
75,milk,1mlp,2.461593e+01,4.948994,0.477485,3.991741,0.028244,0.006995,0.998293,93.333333,6.660039,0.000278,0.710107
76,milk,1svr,2.146577e+01,4.633117,0.475202,3.962725,0.024398,0.005955,0.998529,93.333333,6.712026,0.000496,0.002488
77,ozon,1am,1.192335e+00,1.091939,19.845625,0.907138,0.681594,0.327465,0.936201,83.333333,0.952664,0.000211,0.040698
78,ozon,1amens,1.096404e+00,1.046959,17.586573,0.829687,0.694069,0.287410,0.942683,85.000000,0.893492,0.037225,0.557273
79,ozon,1arima,1.243089e+00,1.114939,17.181052,0.863563,0.864499,0.331024,0.934331,83.333333,inf,inf,inf
80,ozon,1as,1.530417e+00,1.237100,20.603941,0.959387,0.685917,0.353640,0.922609,83.333333,0.816181,0.000270,0.003339
81,ozon,1asens,1.528759e+00,1.235985,21.325465,1.003493,0.706357,0.361198,0.921848,80.000000,0.821550,0.025611,0.227374
82,ozon,1elm,1.088354e+00,1.041701,18.007093,0.849662,0.567123,0.252799,0.945676,83.333333,0.913072,0.000080,0.007683
83,ozon,1mlp,1.208324e+00,1.054151,18.487434,0.842814,0.521904,0.272407,0.940226,86.111111,0.944885,0.000225,0.912665
84,ozon,1svr,2.557373e+00,1.599179,24.027600,1.142297,0.883162,0.677024,0.860362,77.777778,0.809358,0.000556,0.034371
85,pollution,1am,7.821200e+05,884.372760,27.407842,726.431789,0.335503,0.662758,0.742271,69.230769,611.579003,0.000219,0.088035
86,pollution,1amens,8.232504e+05,906.082523,27.676388,735.342705,0.418620,0.720871,0.714610,69.230769,593.532032,0.038404,0.431244
87,pollution,1arima,8.014346e+05,895.228803,29.420365,742.296760,0.924405,1.472344,0.544834,69.230769,inf,inf,inf
88,pollution,1as,6.962394e+05,834.409628,24.778128,680.372908,0.508829,0.814202,0.707646,69.230769,561.056658,0.000288,0.002863
89,pollution,1asens,1.026585e+06,1011.349669,31.085040,832.458807,0.516404,0.728751,0.685342,65.384615,548.014300,0.024275,0.096561
90,pollution,1elm,6.109778e+05,781.570181,24.112819,636.310608,0.286522,0.656123,0.770018,68.461538,658.408900,0.000071,0.006266
91,pollution,1mlp,6.454219e+05,802.745296,24.772284,640.316451,0.301331,0.665078,0.758483,68.461538,641.332905,0.000224,0.242546
92,pollution,1svr,2.588859e+06,1608.993175,43.257618,1273.059171,0.577857,0.829877,0.510933,38.461538,475.907989,0.000450,0.018178
93,recifeaccday,1arima,4.901301e+01,7.000929,21.596595,5.125169,1.233839,1.117764,0.800020,57.485030,inf,inf,inf
94,recifeaccday,1elm,6.304198e+01,7.939435,25.493518,6.173053,2.311938,1.838625,0.709317,57.185629,8.623145,0.000158,0.019813
95,recifeaccday,1mlp,6.613405e+01,8.132224,26.645091,6.355459,3.482874,2.072916,0.685342,56.467066,8.557322,0.000378,1.209122
96,recifeaccday,1scn,6.392959e+01,7.994752,25.167686,6.150944,2.055508,1.738578,0.712694,56.586826,8.567479,0.001382,17.615842
97,recifeaccday,1svr,6.377303e+01,7.985802,25.308427,6.147390,2.723418,1.876641,0.705194,55.089820,8.560863,0.003506,0.041162
98,redwine,1am,9.194152e+04,303.218363,9.085946,236.422440,0.331260,0.324273,0.929216,72.222222,332.951287,0.000133,0.081280
99,redwine,1amens,8.472265e+04,290.944753,9.384137,239.532071,0.294583,0.279995,0.936906,72.777778,342.387017,0.037910,0.395342
100,redwine,1arima,8.474060e+04,291.102394,9.927254,250.674930,0.285100,0.258761,0.939158,72.222222,inf,inf,inf
101,redwine,1as,1.949501e+05,441.531594,13.975622,347.337534,0.393535,0.378715,0.882845,66.666667,316.487319,0.000284,0.012136
102,redwine,1asens,1.136671e+05,336.986829,10.095750,260.958669,0.336599,0.285657,0.924612,75.555556,317.549530,0.027756,0.118082
103,redwine,1elm,1.224913e+05,345.939786,10.032738,251.151124,0.216511,0.258292,0.926511,73.333333,374.736005,0.000078,0.015387
104,redwine,1mlp,1.265623e+05,354.141332,10.213126,252.582595,0.220435,0.260384,0.924637,72.777778,360.503123,0.000250,1.068185
105,redwine,1svr,1.194218e+05,345.574611,11.678677,273.878046,0.186350,0.214611,0.934846,83.333333,293.966196,0.000405,0.003408
106,sunspot,1am,3.637824e+02,19.073071,40.752607,15.840357,0.333690,0.204088,0.950094,60.714286,22.703003,0.000200,0.088501
107,sunspot,1amens,3.584612e+02,18.932991,39.083149,15.567550,0.332064,0.198778,0.951180,60.714286,22.852574,0.043664,0.170933
108,sunspot,1arima,3.654787e+02,19.117498,36.503109,15.719171,0.346894,0.193887,0.951367,67.857143,inf,inf,inf
109,sunspot,1as,3.714122e+02,19.272059,42.700058,16.149458,0.335396,0.208146,0.949048,60.714286,22.119220,0.000284,0.002381
110,sunspot,1asens,3.587203e+02,18.939693,39.453506,15.682219,0.335369,0.200305,0.951012,60.714286,22.514405,0.035891,0.077039
111,sunspot,1elm,3.642087e+02,19.061740,39.472191,15.524575,0.360232,0.178873,0.953340,72.857143,20.790916,0.000082,0.007412
112,sunspot,1mlp,2.886272e+02,16.982771,34.744188,13.763217,0.335739,0.165924,0.960269,75.714286,20.225408,0.000318,1.427423
113,sunspot,1svr,4.140873e+02,20.349135,32.831193,15.496239,0.506440,0.285696,0.937137,82.142857,25.257897,0.000745,0.038204
114,temperature,1am,7.764751e+00,2.786526,4.923363,2.343869,0.411834,0.151257,0.964111,75.000000,2.652628,0.000145,0.079358
115,temperature,1amens,7.688370e+00,2.772481,4.870719,2.324454,0.378107,0.142803,0.965253,78.333333,2.533381,0.044412,1.171151
116,temperature,1arima,8.875264e+00,2.979138,4.968825,2.358477,0.482584,0.162444,0.960140,79.166667,inf,inf,inf
117,temperature,1as,8.202731e+00,2.864041,4.977129,2.360584,0.395545,0.155971,0.962457,75.000000,2.389474,0.000365,0.002747
118,temperature,1asens,7.821548e+00,2.796634,4.942057,2.355732,0.405954,0.149458,0.964129,75.000000,2.397749,0.035273,0.097978
119,temperature,1elm,6.337687e+00,2.515438,4.260413,1.988133,0.336423,0.106642,0.972883,79.166667,2.473030,0.000083,0.015425
120,temperature,1mlp,6.685190e+00,2.580545,4.540404,2.173715,0.355321,0.109487,0.971679,80.000000,2.119724,0.000233,0.433579
121,temperature,1svr,7.130158e+00,2.670235,4.802335,2.308008,0.382437,0.112972,0.970208,79.166667,1.950849,0.000582,0.004552
122,windspeedfortaleza,1arima,1.594682e-01,0.399335,11.597364,0.337112,0.709828,0.282715,0.924707,57.142857,inf,inf,inf
123,windspeedfortaleza,1elm,1.218901e-01,0.348617,10.319095,0.297349,0.624553,0.238008,0.940570,65.000000,0.374543,0.000076,0.018115
124,windspeedfortaleza,1mlp,1.342853e-01,0.356403,10.266502,0.296263,0.576967,0.243374,0.935866,66.428571,0.369995,0.000216,0.048709
125,windspeedfortaleza,1scn,1.270362e-01,0.356112,10.172006,0.296629,0.624027,0.239371,0.939051,65.714286,0.371267,0.000472,0.027073
126,windspeedfortaleza,1svr,1.147182e-01,0.338701,10.062951,0.289563,0.624150,0.264972,0.939855,64.285714,0.367335,0.000259,0.003111
127,windspeednatal,1arima,1.273733e-01,0.356894,8.198806,0.310429,0.942959,0.664290,0.832185,50.000000,inf,inf,inf
128,windspeednatal,1elm,1.712113e-01,0.413293,8.305066,0.314177,1.309030,0.649535,0.800428,58.571429,0.644610,0.000074,0.016414
129,windspeednatal,1mlp,1.612272e-01,0.401521,7.942352,0.302178,1.229742,0.629738,0.809511,57.857143,0.615266,0.000222,0.021069
130,windspeednatal,1scn,1.821379e-01,0.425364,9.086449,0.343558,2.024989,0.639276,0.794388,60.714286,0.626602,0.000657,0.015076
131,windspeednatal,1svr,1.775933e-01,0.421418,8.638145,0.328402,1.443301,0.606314,0.804052,57.142857,0.640044,0.000271,0.001436
132,windspeedrecife,1arima,7.608485e-02,0.275835,12.525556,0.225836,2.064949,0.572282,0.790966,57.142857,inf,inf,inf
133,windspeedrecife,1elm,5.296313e-02,0.229956,9.917462,0.185256,1.116802,0.358321,0.873164,52.142857,0.239491,0.000070,0.008470
134,windspeedrecife,1mlp,8.293656e-02,0.287061,12.656386,0.232808,1.547383,0.496963,0.806580,50.000000,0.229779,0.000223,0.042404
135,windspeedrecife,1scn,7.810539e-02,0.278681,12.303071,0.226784,1.794214,0.469421,0.819684,55.000000,0.240500,0.000475,0.027998
136,windspeedrecife,1svr,5.994352e-02,0.244834,10.580556,0.188903,1.830641,0.514563,0.828876,50.000000,0.251216,0.000269,0.001487
137,woolyrnq,1am,2.064643e+05,454.373691,5.901738,307.702576,0.452714,0.474711,0.885601,74.545455,308.750974,0.000212,0.079310
138,woolyrnq,1amens,2.100414e+05,458.250897,6.187160,320.202634,0.486813,0.529030,0.878389,73.636364,295.882329,0.038746,0.197849
139,woolyrnq,1arima,1.844398e+05,429.464554,6.332390,312.083418,0.469119,0.476445,0.892980,81.818182,inf,inf,inf
140,woolyrnq,1as,2.082389e+05,456.331992,7.091572,360.202335,0.422291,0.551918,0.876701,54.545455,333.012599,0.000221,0.000959
141,woolyrnq,1asens,1.995546e+05,446.655999,6.205228,316.996345,0.482376,0.551196,0.879906,74.545455,312.778128,0.036099,0.100930
142,woolyrnq,1elm,1.999299e+05,446.571170,6.186590,314.057869,0.454555,0.509432,0.883902,81.818182,320.514564,0.000067,0.003808
143,woolyrnq,1mlp,1.985795e+05,445.620769,5.937100,299.314313,0.413833,0.446238,0.891219,81.818182,309.142050,0.000225,0.200475
144,woolyrnq,1svr,2.165572e+05,465.357031,6.256380,320.310225,0.432440,0.494294,0.879241,81.818182,343.675422,0.000369,0.001621

In [58]:
metric = 'RMSE'

proposed_list = []
for k, df in df_mean_metrics.reset_index().groupby('ts'):
    #arima = df[df['model'] == 'arima'][metric].iloc[0]
    #svr = df[df['model'] == 'arima'][metric].iloc[0]
    #mlp = df[df['model'] == 'arima'][metric].iloc[0]

    #df_arima[k] = (df.set_index('model')[metric] < arima)
    #df_svr[k] = (df.set_index('model')[metric] < svr)
    #df_mlp[k] = (df.set_index('model')[metric] < mlp)

    svr_proposed = df[( (df['model'].str.contains("1arimamlpn100s0.6f0.6ccons")))].copy()
    if svr_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(svr_proposed.iloc[svr_proposed['val_metric'].argmin()]).T)

    mlp_proposed = df[( (df['model'].str.contains("mlpkpssfalsep")) )].copy()
    if mlp_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(mlp_proposed.iloc[mlp_proposed['val_metric'].argmin()]).T)

    proposed_list.append(
        df[df['model'].isin(
            [ '1svrval', '1arimaval', '1arimamlp']
        )]
    )

In [59]:
pd.concat(proposed_list)

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
1,consumocoformated,1arimamlpn100s0.6f0.6ccons,12733.683164,112.837401,2.497893,92.655069,1.397332,0.264759,0.936838,70.384615,102.725013,inf,inf
37,consumocoformated,1arimaval,11895.939043,109.068506,2.431796,90.197184,1.347885,0.245301,0.941487,69.230769,inf,inf,inf
40,consumoneformated,1arimamlpn100s0.6f0.6ccons,24534.787245,156.628859,1.619938,130.616899,0.625749,0.18302,0.949934,74.615385,181.476236,inf,inf
76,consumoneformated,1arimaval,24170.785243,155.469564,1.601255,129.085641,0.597026,0.182961,0.950288,69.230769,inf,inf,inf
79,consumonoformated,1arimamlpn100s0.6f0.6ccons,3831.660813,61.899395,1.331784,46.147134,0.376252,0.069594,0.982328,76.923077,72.203646,inf,inf
115,consumonoformated,1arimaval,4113.21355,64.13434,1.365669,47.24827,0.436663,0.074892,0.98098,76.923077,inf,inf,inf
118,consumosdformated,1arimamlpn100s0.6f0.6ccons,233935.5568,483.640919,1.807407,393.370916,0.810606,0.272865,0.928809,61.538462,607.337989,inf,inf
154,consumosdformated,1arimaval,224828.388906,474.160721,1.821033,396.254094,0.841858,0.261272,0.931833,57.692308,inf,inf,inf
157,consumosulformated,1arimamlpn100s0.6f0.6ccons,37595.603319,193.892973,1.895211,160.894473,0.563288,0.222552,0.950645,67.692308,204.695208,inf,inf
193,consumosulformated,1arimaval,36802.791047,191.840535,1.950168,165.356795,0.559145,0.217969,0.951576,65.384615,inf,inf,inf

[]