In [15]:
import pandas as pd
import matplotlib as plt
from metrics import metrics
from model import generics
pd.set_option('display.max_rows', 2000)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
experiment_id = 'pertexps'

In [24]:
df_mean_metrics, df_all_metrics, df_prevs = metrics.open_fold_result(experiment_id)

In [25]:
df_mean_metrics#[df_mean_metrics.reset_index()['model'].str.contains("mlp-").values]

                                       MSE          RMSE         MAPE  \
ts            model
Unemployment  informer        2.136042e+03     46.151129     5.133688
              mlp             1.349703e+03     36.684176     4.423480
              mlpb1100.01     2.117140e+05    417.717804    61.340398
              mlpb1100.1      2.498447e+05    479.735109    72.621311
              mlpb1100.5      7.433792e+04    270.583399    37.963332
              mlpb1200.1      6.634645e+05    744.837769   112.315236
              mlpkpssfalse    1.490616e+03     38.527074     4.870486
              mlpkpssfalsep1  1.393768e+03     37.047272     4.582025
              mlpkpssfalsep2  1.277935e+03     35.725561     4.326842
              mlpkpssfalsep3  1.316745e+03     36.251603     4.341699
              mlpwk0.53       1.971480e+03     44.004157     5.700590
              mlpwk0.54       1.773269e+03     41.194176     5.372648
              mlpwk0.55       1.507650e+03     38.773165     5.065423
              mlpwk0.56       1.996500e+03     43.838318     5.682574
              mlpwk0.57       3.165466e+03     53.600406     7.155131
              mlpwk0.58       2.515914e+03     48.502177     6.351976
              mlpwk0.73       1.502731e+03     38.381658     4.867220
              mlpwk0.74       1.457771e+03     38.134936     4.856538
              mlpwk0.75       1.576416e+03     39.635533     4.943793
              mlpwk0.76       1.703363e+03     40.718614     5.346315
              mlpwk0.77       1.807984e+03     40.639657     5.225897
              mlpwk0.78       2.163848e+03     43.815337     5.507910
              nhits           1.340675e+03     36.609601     4.397119
              tcn             2.682883e+03     50.533605     6.315678
ausbee        informer        5.346556e+02     22.967145     4.208320
              mlp             2.631852e+02     16.210107     2.851759
              mlpb1100.01     3.575722e+04    163.784624    31.283947
              mlpb1100.1      5.705113e+04    221.733703    45.618741
              mlpb1100.5      5.650074e+03     73.168264    13.938335
              mlpb1200.1      2.750461e+05    451.609013    98.623736
              mlpkpssfalse    2.264631e+02     15.039435     2.611031
              mlpkpssfalsep1  3.214154e+02     17.916171     3.228881
              mlpkpssfalsep2  3.081516e+02     17.551963     3.199037
              mlpkpssfalsep3  3.336140e+02     18.258745     3.286238
              mlpwk0.53       5.540044e+02     23.364198     4.401621
              mlpwk0.54       1.114647e+03     32.008499     6.039934
              mlpwk0.55       1.568057e+03     37.224255     6.970878
              mlpwk0.56       1.078253e+03     32.271386     6.143715
              mlpwk0.57       1.583227e+03     38.048213     7.157030
              mlpwk0.58       2.861421e+03     52.079541     9.665700
              mlpwk0.73       5.788244e+02     23.743184     4.474195
              mlpwk0.74       6.542618e+02     24.874732     4.733120
              mlpwk0.75       7.090917e+02     25.842655     4.717886
              mlpwk0.76       8.492487e+02     27.024257     5.171761
              mlpwk0.77       7.082202e+02     25.477814     4.850846
              mlpwk0.78       2.352514e+03     35.627787     6.654386
              nhits           5.116697e+02     22.614458     4.208029
              tcn             7.154756e+02     26.636522     5.070357
austres       informer        3.489381e+02     18.624597     0.079650
              mlp             3.167068e+02     17.795568     0.074989
              mlpb1100.01     4.566687e+06   1815.134265    10.461096
              mlpb1100.1      2.642644e+06   1540.495384     8.873406
              mlpb1100.5      4.787530e+05    541.769683     3.106534
              mlpb1200.1      1.968446e+07   4233.354648    24.399339
              mlpkpssfalse    1.192865e+03     34.313578     0.185933
              mlpkpssfalsep1  3.150096e+02     17.741231     0.086186
              mlpkpssfalsep2  3.009810e+02     17.320027     0.083602
              mlpkpssfalsep3  3.133267e+02     17.687942     0.085582
              mlpwk0.53       3.600049e+02     18.879773     0.092039
              mlpwk0.54       3.210873e+02     17.880736     0.085045
              mlpwk0.55       3.873650e+02     19.511073     0.093496
              mlpwk0.56       3.393750e+02     18.404735     0.088528
              mlpwk0.57       3.823953e+02     19.481075     0.093779
              mlpwk0.58       3.416016e+02     18.456469     0.088401
              mlpwk0.73       3.422562e+02     18.421763     0.088448
              mlpwk0.74       3.449179e+02     18.467557     0.090179
              mlpwk0.75       3.339470e+02     18.250706     0.088397
              mlpwk0.76       3.196602e+02     17.868923     0.086407
              mlpwk0.77       3.261973e+02     18.040943     0.086272
              mlpwk0.78       3.347472e+02     18.266376     0.088096
              nhits           3.698721e+02     19.224911     0.085306
              tcn             3.860152e+02     19.488061     0.088768
coloradoRiver informer        2.569957e-01      0.506890    46.282911
              mlp             2.354172e-01      0.485187    72.333855
              mlpb1100.01     7.053503e+00      2.504817   517.757037
              mlpb1100.1      4.907619e+00      2.142146   500.089032
              mlpb1100.5      3.625400e+00      1.838913   469.415146
              mlpb1200.1      1.949035e+01      4.315023  1088.940716
              mlpb1200.5      1.615188e+01      3.798507   882.005926
              mlpkpssfalse    2.555418e-01      0.505345   100.587067
              mlpkpssfalsep1  2.215224e-01      0.470584    94.100635
              mlpkpssfalsep2  2.311989e-01      0.480615    89.132509
              mlpkpssfalsep3  2.281195e-01      0.477542    87.711670
              mlpwk0.53       3.281215e-01      0.558627    99.906161
              mlpwk0.54       2.395888e-01      0.488885   100.437165
              mlpwk0.55       2.712846e-01      0.518861    98.050901
              mlpwk0.56       2.440071e-01      0.493735    98.479041
              mlpwk0.57       3.160179e-01      0.551220   107.794284
              mlpwk0.58       2.511971e-01      0.500770   102.228932
              mlpwk0.73       2.487177e-01      0.498532   100.763924
              mlpwk0.74       2.597588e-01      0.508826    99.690666
              mlpwk0.75       2.466714e-01      0.496155   100.586762
              mlpwk0.76       2.372534e-01      0.486269    97.067066
              mlpwk0.77       2.541468e-01      0.503430   108.179269
              mlpwk0.78       2.593054e-01      0.508127   101.983698
              nhits           2.565544e-01      0.506223    67.307581
              tcn             2.702826e-01      0.519240    64.598878
gasoline      informer        9.352776e+04    305.757897     2.658203
              mlp             6.143358e+04    247.857283     2.199466
              mlpb1100.01     5.829963e+06   2108.526528    20.545039
              mlpb1100.1      2.794790e+06   1583.582822    15.789304
              mlpb1100.5      4.824091e+05    686.806250     6.235342
              mlpb1200.1      7.371528e+06   2429.931322    23.720851
              mlpkpssfalse    6.423301e+04    253.439420     2.320492
              mlpkpssfalsep1  6.526817e+04    255.465710     2.338420
              mlpkpssfalsep2  6.610349e+04    257.101749     2.353667
              mlpkpssfalsep3  6.556649e+04    256.054268     2.340723
              mlpwk0.53       6.957116e+04    263.486023     2.404990
              mlpwk0.54       6.858766e+04    261.654009     2.394369
              mlpwk0.55       6.750775e+04    259.629857     2.373327
              mlpwk0.56       7.214384e+04    268.401476     2.462189
              mlpwk0.57       6.433148e+04    253.522328     2.305643
              mlpwk0.58       6.813462e+04    260.694838     2.377674
              mlpwk0.73       7.531576e+04    274.111084     2.522452
              mlpwk0.74       6.663694e+04    257.882236     2.352385
              mlpwk0.75       7.768346e+04    275.834011     2.487609
              mlpwk0.76       6.700820e+04    258.757796     2.361607
              mlpwk0.77       6.640076e+04    257.577376     2.345503
              mlpwk0.78       6.962090e+04    263.533286     2.418523
              nhits           9.839014e+04    313.588940     2.731089
              tcn             1.063113e+05    325.704825     2.850207
heartrate     informer        1.787667e+00      1.328662     1.153367
              mlp             1.072802e+00      1.021460     1.002817
              mlpb1100.01     3.031165e+02     15.218858    15.557260
              mlpb1100.1      1.700124e+02     12.160905    12.429424
              mlpb1100.5      2.206591e+01      4.467966     4.275590
              mlpb1200.1      5.954698e+02     23.701104    24.171288
              mlpkpssfalse    1.366866e+00      1.145897     1.144796
              mlpkpssfalsep1  1.046073e+00      1.001260     0.992879
              mlpkpssfalsep2  7.250837e+00      1.852792     1.578048
              mlpkpssfalsep3  1.459158e+00      1.180794     1.144026
              mlpwk0.53       1.584876e+00      1.098804     0.991079
              mlpwk0.54       7.282800e-01      0.844811     0.789823
              mlpwk0.55       8.207317e+00      1.643078     1.552685
              mlpwk0.56       7.109392e-01      0.838619     0.771847
              mlpwk0.57       6.594739e-01      0.808339     0.728211
              mlpwk0.58       9.359818e-01      0.909718     0.814566
              mlpwk0.73       1.072261e+00      0.888851     0.778499
              mlpwk0.74       2.157547e+00      1.243266     1.063321
              mlpwk0.75       1.227231e+00      0.936949     0.860560
              mlpwk0.76       6.685963e-01      0.814003     0.749892
              mlpwk0.77       3.935280e+00      1.240165     1.070739
              mlpwk0.78       1.147410e+00      0.969854     0.878863
              nhits           7.899946e-01      0.888082     0.796513
              tcn             1.377388e+00      1.155629     0.992446
melbmin       nhits           6.536273e+00      2.556387    22.181713
              tcn             5.300614e+00      2.301047    21.136991
milk          informer        2.067735e+02     14.226442     1.035895
              mlp             3.657512e+01      6.042718     0.583869
              mlpb1100.01     3.725544e+05    527.295575    58.234193
              mlpb1100.1      2.426014e+05    456.044264    49.724307
              mlpb1100.5      1.206153e+04    105.909273    10.290766
              mlpb1200.1      3.167353e+05    535.912523    56.791442
              mlpb1200.5      1.632221e+04    125.522402    12.277185
              mlpkpssfalse    1.129161e+02     10.495259     1.000172
              mlpkpssfalsep1  1.256604e+02     10.701730     1.004730
              mlpkpssfalsep2  2.478786e+02     14.344669     1.279028
              mlpkpssfalsep3  9.426373e+01      9.652869     0.908673
              mlpwk0.53       3.774220e+03     51.073624     4.263548
              mlpwk0.54       1.677702e+06    693.539743    40.736932
              mlpwk0.55       4.936229e+04    167.826344    14.826157
              mlpwk0.56       5.702110e+03     57.998026     5.558245
              mlpwk0.57       1.426769e+03     35.194204     3.325238
              mlpwk0.58       2.477433e+05    359.776913    33.170415
              mlpwk0.73       1.569394e+03     28.716887     2.556422
              mlpwk0.74       1.195827e+04     55.730979     4.706730
              mlpwk0.75       3.690607e+02     17.077246     1.555617
              mlpwk0.76       4.563019e+03     49.714625     4.339812
              mlpwk0.77       1.040900e+04     56.145421     5.041280
              mlpwk0.78       1.062571e+03     28.971113     2.633321
              nhits           4.390742e+01      6.618995     0.593260
              tcn             4.585230e+01      6.762272     0.669487
ozon          informer        1.428808e+00      1.192971    18.900523
              mlp             1.031090e+00      1.015369    19.308518
              mlpb1100.01     2.197327e+01      4.418471    89.591982
              mlpb1100.1      1.346416e+01      3.485433    67.174474
              mlpb1100.5      1.346569e+01      3.552203    73.664592
              mlpb1200.1      5.431737e+01      7.063538   152.212518
              mlpkpssfalse    1.050271e+00      1.024809    19.515980
              mlpkpssfalsep1  9.544358e-01      0.976909    19.060170
              mlpkpssfalsep2  1.902311e+00      1.276303    24.227526
              mlpkpssfalsep3  1.338657e+00      1.115263    21.881944
              mlpwk0.53       4.876791e+00      2.036115    38.261170
              mlpwk0.54       3.918794e+00      1.902984    36.392543
              mlpwk0.55       5.942306e+00      2.320073    46.601326
              mlpwk0.56       7.760572e+00      2.698635    52.176285
              mlpwk0.57       1.306356e+01      3.316244    67.295524
              mlpwk0.58       8.801809e+00      2.816080    54.083846
              mlpwk0.73       4.672734e+00      1.885891    34.993074
              mlpwk0.74       5.372174e+00      2.114200    40.428965
              mlpwk0.75       4.954738e+00      1.989521    37.554529
              mlpwk0.76       6.152912e+00      2.331409    47.029018
              mlpwk0.77       6.193857e+00      2.209304    40.652376
              mlpwk0.78       3.426713e+00      1.759312    33.909863
              nhits           1.152016e+00      1.072986    18.546214
              tcn             1.834867e+00      1.347704    22.435775
pollution     informer        5.850613e+05    761.425320    19.829639
              mlp             5.416193e+05    735.711944    21.078495
              mlpb1100.01     1.912699e+07   3720.977902   108.165200
              mlpb1100.1      1.498622e+07   3616.123328   102.568713
              mlpb1100.5      4.590270e+06   2109.812153    57.590550
              mlpb1200.1      6.333892e+07   7195.715706   215.713156
              mlpkpssfalse    4.820037e+05    694.139458    18.053315
              mlpkpssfalsep1  6.798636e+05    805.128880    21.585461
              mlpkpssfalsep2  5.182499e+05    719.690854    19.950049
              mlpkpssfalsep3  5.266286e+05    725.274207    20.097435
              mlpwk0.53       3.821064e+06   1829.397004    47.994519
              mlpwk0.54       5.695187e+06   2200.691150    56.179274
              mlpwk0.55       1.541842e+07   3430.816628    87.337356
              mlpwk0.56       7.534758e+06   2450.422877    62.233789
              mlpwk0.57       1.539781e+07   3387.377341    88.705470
              mlpwk0.58       1.561467e+07   3329.772663    82.347304
              mlpwk0.73       1.262292e+06   1114.453365    30.274874
              mlpwk0.74       2.368859e+06   1459.946780    39.816656
              mlpwk0.75       2.118310e+06   1401.250614    37.128575
              mlpwk0.76       1.423787e+07   2991.396233    68.526058
              mlpwk0.77       1.025916e+07   2607.282171    62.327611
              mlpwk0.78       2.573391e+07   3435.352307    80.198960
              nhits           3.944871e+05    627.718935    16.214629
              tcn             7.960342e+05    886.666550    24.712035
redwine       informer        3.603573e+05    597.939189    24.533752
              mlp             1.434031e+05    367.180201    13.265162
              mlpb1100.01     8.686534e+06   2728.227033   116.957067
              mlpb1100.1      3.997297e+06   1904.211996    81.087471
              mlpb1100.5      1.808072e+06   1325.542810    54.658588
              mlpb1200.1      1.039355e+07   3124.842647   123.084718
              mlpkpssfalse    1.416135e+05    376.057548    13.400169
              mlpkpssfalsep1  2.124821e+05    459.054658    15.979739
              mlpkpssfalsep2  1.905891e+05    436.120892    14.691126
              mlpkpssfalsep3  2.141279e+05    461.367136    15.658233
              mlpwk0.53       1.614564e+06   1199.062301    40.464632
              mlpwk0.54       1.085312e+06    941.840961    35.253212
              mlpwk0.55       1.065784e+06    935.467244    33.246737
              mlpwk0.56       1.394862e+06   1028.109182    36.917536
              mlpwk0.57       1.190251e+07   2194.946737    79.302805
              mlpwk0.58       2.696267e+06   1449.831834    55.369428
              mlpwk0.73       2.585619e+05    501.278589    18.474354
              mlpwk0.74       4.542471e+05    637.536508    22.050278
              mlpwk0.75       4.046816e+05    595.198315    21.413857
              mlpwk0.76       6.217517e+05    731.832137    25.462730
              mlpwk0.77       4.292095e+05    627.916521    23.044422
              mlpwk0.78       5.403901e+05    694.373652    25.247840
              nhits           2.182760e+05    466.835236    17.747350
              tcn             3.512380e+05    590.043407    20.152465
sunspot       informer        4.361967e+02     20.816421    34.588803
              mlp             3.840394e+02     19.595571    32.117264
              mlpb1100.01     1.668708e+04    125.825858   364.470254
              mlpb1100.1      1.893155e+04    135.505305   433.670014
              mlpb1100.5      6.350516e+03     78.554777   231.465636
              mlpb1200.1      3.578227e+04    181.693075   531.255348
              mlpb1200.5      3.506431e+04    182.498153   495.602498
              mlpkpssfalse    4.580465e+02     20.979362    37.731383
              mlpkpssfalsep1  4.255630e+02     20.549877    33.998428
              mlpkpssfalsep2  3.960325e+02     19.900071    30.293466
              mlpkpssfalsep3  4.210353e+02     20.472083    32.843788
              mlpwk0.53       8.260750e+02     27.279158    57.984010
              mlpwk0.54       5.276101e+02     22.868009    47.230470
              mlpwk0.55       5.887183e+02     23.866512    51.926914
              mlpwk0.56       8.075325e+02     27.135730    56.020603
              mlpwk0.57       6.153366e+02     24.514809    53.840615
              mlpwk0.58       7.511158e+02     27.034178    57.681219
              mlpwk0.73       1.340291e+03     33.667077    75.355578
              mlpwk0.74       5.612225e+02     23.588785    44.202192
              mlpwk0.75       4.975048e+02     22.233279    44.204889
              mlpwk0.76       5.297232e+02     22.839570    45.415264
              mlpwk0.77       5.633862e+02     23.400900    45.454437
              mlpwk0.78       9.247552e+02     27.829518    61.227846
              nhits           4.215341e+02     20.525296    31.838025
              tcn             9.224702e+02     29.350342    46.757457
temperature   informer        8.122858e+00      2.842139     5.084307
              mlp             5.494202e+00      2.342424     4.111487
              mlpb1100.01     4.834935e+02     20.518185    37.973211
              mlpb1100.1      3.036764e+02     16.522640    29.032822
              mlpb1100.5      1.058597e+02     10.046437    16.873534
              mlpb1200.1      4.865468e+02     21.440932    36.004432
              mlpkpssfalse    5.574596e+00      2.355331     4.074320
              mlpkpssfalsep1  9.660172e+00      2.940978     4.915713
              mlpkpssfalsep2  6.641091e+00      2.575992     4.469447
              mlpkpssfalsep3  6.874667e+00      2.620456     4.611576
              mlpwk0.53       1.251765e+01      3.511683     5.928805
              mlpwk0.54       2.253688e+01      4.334575     7.269982
              mlpwk0.55       1.923613e+01      4.177170     7.153709
              mlpwk0.56       3.875189e+01      5.586053     9.319963
              mlpwk0.57       2.125825e+01      4.510651     7.601867

In [9]:
metric = 'RMSE'

proposed_list = []
for k, df in df_mean_metrics.reset_index().groupby('ts'):
    #arima = df[df['model'] == 'arima'][metric].iloc[0]
    #svr = df[df['model'] == 'arima'][metric].iloc[0]
    #mlp = df[df['model'] == 'arima'][metric].iloc[0]

    #df_arima[k] = (df.set_index('model')[metric] < arima)
    #df_svr[k] = (df.set_index('model')[metric] < svr)
    #df_mlp[k] = (df.set_index('model')[metric] < mlp)

    svr_proposed = df[( (df['model'].str.contains("mlpwk1")))].copy()
    if svr_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(svr_proposed.iloc[svr_proposed['val_metric'].argmin()]).T)

    mlp_proposed = df[( (df['model'].str.contains("mlpkpssfalsep")) )].copy()
    if mlp_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(mlp_proposed.iloc[mlp_proposed['val_metric'].argmin()]).T)

    proposed_list.append(
        df[df['model'].isin(
            [ 'mlp']
        )]
    )

In [10]:
pd.concat(proposed_list)

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
23,Unemployment,mlpwk15,1217.130081,34.85137,4.216812,25.233526,0.390715,0.116971,0.972307,73.75,26.821242,inf,inf
8,Unemployment,mlpkpssfalsep3,1316.745225,36.251603,4.341699,26.338199,0.510706,0.140448,0.968465,75.416667,24.69539,inf,inf
0,Unemployment,mlp,1349.70336,36.684176,4.42348,26.69181,0.494122,0.14909,0.96717,78.541667,27.591381,0.000256,0.420111
48,ausbee,mlpwk13,391.007244,19.673637,3.595159,15.493961,0.082525,0.167263,0.947901,91.190476,38.093646,inf,inf
35,ausbee,mlpkpssfalsep3,333.613995,18.258745,3.286238,14.214244,0.07167,0.146486,0.95491,94.761905,19.057366,inf,inf
27,ausbee,mlp,263.18521,16.210107,2.851759,12.132077,0.064744,0.1348,0.961435,94.761905,19.60374,0.000286,0.361878
75,austres,mlpwk13,330.661726,18.055612,0.08747,15.110663,0.111584,0.005208,0.998711,88.823529,24.907492,inf,inf
60,austres,mlpkpssfalsep1,315.009608,17.741231,0.086186,14.883686,0.102546,0.004923,0.998777,88.235294,23.57158,inf,inf
54,austres,mlp,316.706755,17.795568,0.074989,12.95803,0.107342,0.004952,0.99877,88.235294,8.936424,0.000225,0.234992
103,coloradoRiver,mlpwk13,0.249591,0.4982,95.448,0.311496,1.276697,0.8291,0.803147,65.675676,0.753442,inf,inf
89,coloradoRiver,mlpkpssfalsep2,0.231199,0.480615,89.132509,0.292405,1.162407,0.800656,0.812755,64.391892,0.694652,inf,inf
81,coloradoRiver,mlp,0.235417,0.485187,72.333855,0.259857,0.958569,0.736469,0.813605,63.243243,0.763438,0.000302,0.498848
133,gasoline,mlpwk15,67663.893667,259.9432,2.383199,214.756741,14.17632,1.47347,0.705833,42.95302,322.361197,inf,inf
116,gasoline,mlpkpssfalsep1,65268.167252,255.46571,2.33842,210.664789,17.327566,1.452588,0.713258,43.087248,319.831102,inf,inf
110,gasoline,mlp,61433.57555,247.857283,2.199466,196.399634,12.958859,1.302964,0.740158,40.134228,315.449839,0.000254,0.523039
160,heartrate,mlpwk15,0.607044,0.775486,0.728617,0.639888,0.283728,0.02047,0.994911,60.666667,0.61329,inf,inf
144,heartrate,mlpkpssfalsep2,7.250837,1.852792,1.578048,1.344454,2.09299,0.092892,0.96563,56.0,0.545248,inf,inf
137,heartrate,mlp,1.072802,1.02146,1.002817,0.868131,0.707717,0.03995,0.990517,54.666667,0.681373,0.000257,0.605355
187,milk,mlpwk14,834.597954,22.646144,2.082348,17.578888,0.478569,0.177903,0.943389,87.741935,20.518912,inf,inf
172,milk,mlpkpssfalsep2,247.878591,14.344669,1.279028,10.789984,0.183733,0.072213,0.98151,91.290323,17.115862,inf,inf
164,milk,mlp,36.575117,6.042718,0.583869,4.873061,0.033055,0.011123,0.997255,94.193548,7.569486,0.000678,0.468287
214,ozon,mlpwk13,1.94059,1.302547,25.240294,1.046808,0.603375,0.321131,0.90134,70.555556,1.904026,inf,inf
200,ozon,mlpkpssfalsep2,1.902311,1.276303,24.227526,1.014209,0.569571,0.313378,0.904513,80.0,1.065401,inf,inf
193,ozon,mlp,1.03109,1.015369,19.308518,0.818239,0.613578,0.245092,0.938248,71.944444,1.117851,0.000279,0.224784
242,pollution,mlpwk14,945644.097904,945.710735,25.646246,770.472233,0.439679,0.836909,0.72217,71.153846,1850.930134,inf,inf
227,pollution,mlpkpssfalsep2,518249.87759,719.690854,19.950049,589.606092,0.55714,1.026995,0.770623,71.538462,953.432658,inf,inf
220,pollution,mlp,541619.282335,735.711944,21.078495,607.614631,0.332088,0.695393,0.805884,70.769231,431.269911,0.000288,0.282004
269,redwine,mlpwk14,205473.883505,444.465713,16.449534,353.785616,0.667204,0.70054,0.841954,65.945946,556.595957,inf,inf
253,redwine,mlpkpssfalsep1,212482.090567,459.054658,15.979739,364.865304,1.192058,0.986146,0.810844,62.702703,282.73943,inf,inf
247,redwine,mlp,143403.090121,367.180201,13.265162,276.707918,0.369692,0.389581,0.902132,65.675676,237.434781,0.000268,1.016695
296,sunspot,mlpwk13,448.747171,21.107783,37.559837,15.780235,0.383333,0.199377,0.952653,74.912281,19.78346,inf,inf
281,sunspot,mlpkpssfalsep1,425.563047,20.549877,33.998428,15.071228,0.388018,0.187487,0.955324,80.877193,14.554581,inf,inf
274,sunspot,mlp,384.039361,19.595571,32.117264,14.324324,0.359634,0.170657,0.959721,81.578947,12.799614,0.00033,1.85332
324,temperature,mlpwk13,8.895282,2.97693,5.126143,2.405418,0.288469,0.118922,0.968333,74.166667,3.090635,inf,inf
311,temperature,mlpkpssfalsep3,6.874667,2.620456,4.611576,2.143725,0.265422,0.098525,0.97477,78.125,2.80033,inf,inf
303,temperature,mlp,5.494202,2.342424,4.111487,1.89343,0.267442,0.081361,0.979594,76.458333,2.62213,0.000274,0.728755
351,woolyrnq,mlpwk13,14938597.774537,2898.661156,34.996669,1667.947292,0.467432,0.969981,0.346882,56.956522,1353.394367,inf,inf
337,woolyrnq,mlpkpssfalsep2,997274.944355,932.776089,14.517046,685.521872,0.563135,0.832828,0.616118,67.826087,403.765643,inf,inf
330,woolyrnq,mlp,334464.080676,537.029952,8.345252,402.735047,0.374754,0.58421,0.811371,81.304348,378.942384,0.000286,0.921087