In [61]:
import pandas as pd
import matplotlib as plt
from metrics import metrics
from model import generics
pd.set_option('display.max_rows', 2000)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [62]:
experiment_id = 'consumoenergia'

In [63]:
df_mean_metrics, df_all_metrics, df_prevs = metrics.open_fold_result(experiment_id)

In [64]:
df_mean_metrics#[df_mean_metrics.reset_index()['model'].str.contains("mlp-").values]

                                        MSE        RMSE      MAPE         MAE  \
ts                 model
consumocoformated  1arima      10454.794078  102.248687  2.143203   81.733874
                   1arimamlp   10939.885911  104.592572  2.229568   84.983013
                   1arimascn   10813.478863  103.980552  2.211784   84.284295
                   1arimasvr   10792.753612  103.888178  2.150178   81.896423
                   1deepar     19856.085965  140.786119  2.950621  112.429787
                   1kan        16834.548332  129.718507  2.883273  109.409203
                   1mlp        11197.797098  105.813849  2.176744   82.959226
                   1nhits      16251.759605  127.455604  2.867061  108.372834
                   1scn        11532.778051  107.316494  2.173880   82.854555
                   1svr        11809.468468  108.671378  2.256008   86.000395
                   1tcn        24183.733641  154.974174  3.464050  130.642570
                   3arima      25387.811595  159.335531  3.084819  117.600443
                   3mlp        31322.548890  176.977125  3.434200  131.031596
                   3scn        32143.143498  179.252947  3.510384  134.005079
                   3svr        31862.251234  178.500003  3.538390  135.025075
consumoneformated  1arima      25196.698224  158.734679  1.573869  130.055796
                   1arimamlp   25723.455747  160.374722  1.610255  133.020651
                   1arimascn   25987.460952  161.189334  1.629806  134.599473
                   1arimasvr   28761.782711  169.592991  1.718175  141.934312
                   1deepar     42780.603753  206.260370  2.012775  165.859382
                   1kan        34363.445855  185.364853  1.716799  142.569539
                   1mlp        24194.158996  155.433113  1.437450  118.806668
                   1nhits      38638.272908  196.559553  1.929683  159.246249
                   1scn        27300.739805  164.895862  1.514642  125.336900
                   1svr        27156.423368  164.792061  1.562319  129.537177
                   1tcn        40121.091176  199.874571  1.964241  162.276014
                   3arima      37148.369042  192.739122  1.963928  163.650970
                   3mlp        48041.827665  218.724459  1.982325  165.256424
                   3scn        47805.955968  218.390512  1.993276  166.027893
                   3svr        39780.224513  199.449804  1.846383  153.285412
consumonoformated  1arima       3123.031014   55.884086  1.257406   45.612850
                   1arimamlp    3343.974459   57.823202  1.313483   47.810024
                   1arimascn    3284.411976   57.305768  1.293816   47.069218
                   1arimasvr    3150.694987   56.131052  1.268902   46.031271
                   1deepar      6801.515344   81.464377  1.724169   62.152550
                   1kan         4855.218992   69.635238  1.634099   59.175399
                   1mlp         4675.686234   68.373357  1.437966   52.520975
                   1nhits       5184.378219   71.886601  1.620453   58.386565
                   1scn         5315.973882   72.593853  1.601398   58.097855
                   1svr         4458.369208   66.771021  1.517553   54.790081
                   1tcn         8956.725402   94.172780  2.015137   72.743512
                   3arima       6534.974625   80.839190  1.858114   67.560232
                   3mlp        11872.256115  108.953362  2.316351   85.380540
                   3scn        10000.523463   99.359897  2.173283   79.524361
                   3svr        12065.889760  109.844844  2.601044   94.919188
consumosdformated  1arima     213268.327773  461.809839  1.607485  359.406737
                   1arimamlp  212042.530276  460.420546  1.596945  357.007752
                   1arimascn  201043.495912  448.362473  1.555042  347.849377
                   1arimasvr  205948.656564  453.815664  1.573703  351.908902
                   1deepar    447988.126060  669.315092  2.512697  555.921995
                   1kan       274073.511362  523.369473  1.788859  395.927499
                   1mlp       234411.610194  484.152678  1.770277  393.261498
                   1nhits     286074.705702  534.814711  1.794395  398.427191
                   1scn       238226.448218  488.026145  1.777506  395.058155
                   1svr       266870.936028  516.595525  1.903986  422.972814
                   1tcn       414975.180216  639.574437  2.303670  511.557019
                   3arima     417487.749953  646.132920  2.412966  536.056504
                   3mlp       651681.485423  807.254355  2.759209  613.831994
                   3scn       685427.253303  827.592449  2.921223  648.222234
                   3svr       650420.730730  806.486659  2.757292  613.087784
consumosulformated 1arima      51257.881035  226.402034  2.077571  179.328356
                   1arimamlp   54392.425410  233.154399  2.032968  175.685347
                   1arimascn   64564.474307  252.852648  2.181614  189.187378
                   1arimasvr   76531.870065  276.643941  2.407948  210.949350
                   1deepar     72449.605889  267.841757  2.289974  197.227874
                   1kan        96484.437477  310.590506  2.468131  212.161961
                   1mlp        75760.270545  275.225352  2.246081  193.534453
                   1nhits      88079.889765  296.667257  2.569297  221.132783
                   1scn        80272.716481  282.928425  2.253912  193.943641
                   1svr        77804.834492  278.935180  2.335585  201.055332
                   1tcn        91830.247943  301.954172  2.638775  226.454285
                   3arima      64488.833049  253.946516  2.640037  225.661802
                   3mlp        90130.010823  300.190976  2.814474  241.305569
                   3scn        98267.512334  313.196196  3.098852  263.914389
                   3svr       142273.834313  377.192039  3.823687  329.784567

                                 theil       ARV        IA      POCID  \
ts                 model
consumocoformated  1arima     0.788507  0.442205  0.902407  71.428571
                   1arimamlp  0.829263  0.459326  0.898173  72.500000
                   1arimascn  0.818695  0.453824  0.899471  73.214286
                   1arimasvr  0.842534  0.474197  0.897568  75.000000
                   1deepar    1.124312  0.685325  0.823259  63.928571
                   1kan       0.755651  0.533364  0.860943  66.428571
                   1mlp       0.553180  0.368235  0.907495  71.071429
                   1nhits     0.668504  0.547798  0.858519  62.857143
                   1scn       0.549272  0.383522  0.903774  71.785714
                   1svr       0.586045  0.404627  0.899971  75.000000
                   1tcn       0.583225  0.608318  0.816469  51.785714
                   3arima     3.683039  1.023582  0.773245  75.000000
                   3mlp       2.283467  0.900457  0.758905  63.214286
                   3scn       2.277090  0.913905  0.754113  61.785714
                   3svr       2.331442  0.878630  0.759183  64.285714
consumoneformated  1arima     0.571590  0.394447  0.899778  67.857143
                   1arimamlp  0.557819  0.387302  0.899560  67.500000
                   1arimascn  0.566321  0.378223  0.900214  66.428571
                   1arimasvr  0.528141  0.414317  0.889355  64.285714
                   1deepar    1.418777  0.567906  0.838650  57.500000
                   1kan       0.837565  0.429644  0.877018  70.357143
                   1mlp       0.776111  0.349863  0.907837  72.500000
                   1nhits     0.843107  0.520405  0.852352  56.428571
                   1scn       0.789437  0.394462  0.895764  71.071429
                   1svr       0.656475  0.369382  0.900020  71.428571
                   1tcn       0.647743  0.494404  0.854470  63.928571
                   3arima     1.408585  0.472231  0.866003  78.571429
                   3mlp       2.145932  0.628426  0.822716  60.000000
                   3scn       1.935144  0.632947  0.822096  65.000000
                   3svr       1.286680  0.451975  0.866775  82.142857
consumonoformated  1arima     0.235997  0.103946  0.974367  82.142857
                   1arimamlp  0.238513  0.111064  0.972538  82.142857
                   1arimascn  0.240481  0.109870  0.972947  82.500000
                   1arimasvr  0.233700  0.104580  0.974170  82.142857
                   1deepar    0.463486  0.183082  0.948812  74.642857
                   1kan       0.246135  0.146515  0.961670  72.142857
                   1mlp       0.325491  0.166632  0.959989  76.785714
                   1nhits     0.205786  0.155799  0.959071  72.142857
                   1scn       0.272296  0.173727  0.956161  77.142857
                   1svr       0.250981  0.151030  0.962774  78.571429
                   1tcn       0.209567  0.209443  0.937636  74.285714
                   3arima     0.574880  0.239740  0.943189  75.000000
                   3mlp       1.151448  0.461082  0.888766  68.214286
                   3scn       0.572600  0.276585  0.922341  72.857143
                   3svr       0.331546  0.251167  0.919497  75.000000
consumosdformated  1arima     0.861470  0.395097  0.897859  64.285714
                   1arimamlp  0.839664  0.392302  0.898499  63.928571
                   1arimascn  0.878789  0.380388  0.903147  66.785714
                   1arimasvr  0.923414  0.397322  0.899368  64.285714
                   1deepar    1.263931  0.554015  0.816935  51.071429
                   1kan       0.907126  0.355343  0.890783  63.928571
                   1mlp       0.924751  0.383015  0.894410  67.500000
                   1nhits     0.820792  0.367889  0.886171  59.642857
                   1scn       0.913728  0.389652  0.892362  64.285714
                   1svr       1.056347  0.449128  0.877162  60.714286
                   1tcn       0.539206  0.440314  0.849306  59.285714
                   3arima     1.551842  0.780171  0.797398  57.142857
                   3mlp       2.316111  0.963846  0.713096  48.928571
                   3scn       2.278433  1.002388  0.697503  47.142857
                   3svr       2.568071  0.966603  0.710194  53.571429
consumosulformated 1arima     0.468971  0.227158  0.945406  57.142857
                   1arimamlp  0.484822  0.230511  0.943339  61.785714
                   1arimascn  0.515946  0.280465  0.931344  65.000000
                   1arimasvr  0.535568  0.403223  0.909107  57.142857
                   1deepar    0.516637  0.205812  0.938265  70.000000
                   1kan       0.659959  0.310093  0.910421  68.928571
                   1mlp       0.492392  0.273305  0.926443  70.714286
                   1nhits     0.507852  0.280926  0.919416  66.071429
                   1scn       0.476017  0.283092  0.922770  65.714286
                   1svr       0.480841  0.272155  0.925509  71.428571
                   1tcn       0.431437  0.277323  0.918412  58.571429
                   3arima     1.150481  0.394656  0.919390  60.714286
                   3mlp       0.993670  0.355809  0.907664  63.214286
                   3scn       0.872654  0.290504  0.913125  65.357143
                   3svr       1.576464  0.761497  0.821798  64.285714

                              val_metric  time_testing  time_training
ts                 model
consumocoformated  1arima            inf           inf            inf
                   1arimamlp   83.944253      0.000182       0.014439
                   1arimascn   85.857653      0.000302       0.119466
                   1arimasvr   81.650664      0.000561       0.006431
                   1deepar    107.525281           inf            inf
                   1kan        99.980791           inf            inf
                   1mlp        87.342742      0.000220       0.027943
                   1nhits      89.574250           inf            inf
                   1scn        92.414214      0.000307       0.175806
                   1svr        85.692920      0.000556       0.010252
                   1tcn       131.893937           inf            inf
                   3arima            inf           inf            inf
                   3mlp        88.988527      0.000379       0.036477
                   3scn        95.402566      0.001744       0.915693
                   3svr        81.277919      0.000425       0.006635
consumoneformated  1arima            inf           inf            inf
                   1arimamlp  132.167538      0.000232       0.025194
                   1arimascn  139.854226      0.000310       0.131526
                   1arimasvr  127.070220      0.000407       0.008133
                   1deepar    194.878162           inf            inf
                   1kan       159.278363           inf            inf
                   1mlp       189.443907      0.000225       0.071239
                   1nhits     161.184493           inf            inf
                   1scn       187.764228      0.000665       0.383843
                   1svr       169.733535      0.000216       0.013487
                   1tcn       214.757637           inf            inf
                   3arima            inf           inf            inf
                   3mlp       220.359647      0.000322       1.190955
                   3scn       223.181645      0.001744       0.707515
                   3svr       195.388470      0.000453       0.009248
consumonoformated  1arima            inf           inf            inf
                   1arimamlp   76.480367      0.000257       0.206176
                   1arimascn   77.263675      0.002882       0.432990
                   1arimasvr   75.720402      0.000222       0.001688
                   1deepar    113.488435           inf            inf
                   1kan        99.582526           inf            inf
                   1mlp        95.359777      0.000282       0.042069
                   1nhits      79.431290           inf            inf
                   1scn        90.953213      0.000689       0.381149
                   1svr        85.485164      0.000373       0.027594
                   1tcn        95.111504           inf            inf
                   3arima            inf           inf            inf
                   3mlp       145.576197      0.000214       0.024842
                   3scn       129.198952      0.000799       0.406617
                   3svr       117.961058      0.000404       0.031813
consumosdformated  1arima            inf           inf            inf
                   1arimamlp  456.290710      0.000271       0.014813
                   1arimascn  497.026504      0.000723       0.337178
                   1arimasvr  467.657957      0.000455       0.005146
                   1deepar    755.127673           inf            inf
                   1kan       645.933864           inf            inf
                   1mlp       525.067831      0.000290       0.066537
                   1nhits     548.179696           inf            inf
                   1scn       527.943837      0.000349       0.218556
                   1svr       498.538385      0.000420       0.009381
                   1tcn       789.533127           inf            inf
                   3arima            inf           inf            inf
                   3mlp       670.525153      0.000257       0.094444
                   3scn       700.595266      0.000319       0.109874
                   3svr       622.384618      0.000427       0.005908
consumosulformated 1arima            inf           inf            inf
                   1arimamlp  209.592373      0.000269       0.224756
                   1arimascn  209.578743      0.001771       1.560869
                   1arimasvr  198.295361      0.000517       0.158780
                   1deepar    250.630326           inf            inf
                   1kan       270.245151           inf            inf
                   1mlp       253.818642      0.000332       0.506504
                   1nhits     245.347754           inf            inf
                   1scn       257.563921      0.000342       0.199406
                   1svr       240.677470      0.000185       0.004945
                   1tcn       289.359391           inf            inf
                   3arima            inf           inf            inf
                   3mlp       372.355707      0.000282       0.737660
                   3scn       337.717644      0.000959       0.645221
                   3svr       252.154211      0.000560       0.181924

In [4]:
metric = 'RMSE'

proposed_list = []
for k, df in df_mean_metrics.reset_index().groupby('ts'):
    #arima = df[df['model'] == 'arima'][metric].iloc[0]
    #svr = df[df['model'] == 'arima'][metric].iloc[0]
    #mlp = df[df['model'] == 'arima'][metric].iloc[0]

    #df_arima[k] = (df.set_index('model')[metric] < arima)
    #df_svr[k] = (df.set_index('model')[metric] < svr)
    #df_mlp[k] = (df.set_index('model')[metric] < mlp)

    svr_proposed = df[( (df['model'].str.contains("mlpwk1")))].copy()
    if svr_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(svr_proposed.iloc[svr_proposed['val_metric'].argmin()]).T)

    mlp_proposed = df[( (df['model'].str.contains("mlpkpssfalsep")) )].copy()
    if mlp_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(mlp_proposed.iloc[mlp_proposed['val_metric'].argmin()]).T)

    proposed_list.append(
        df[df['model'].isin(
            [ 'mlp']
        )]
    )

NameError: name 'df_mean_metrics' is not defined

In [10]:
pd.concat(proposed_list)

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
23,Unemployment,mlpwk15,1217.130081,34.85137,4.216812,25.233526,0.390715,0.116971,0.972307,73.75,26.821242,inf,inf
8,Unemployment,mlpkpssfalsep3,1316.745225,36.251603,4.341699,26.338199,0.510706,0.140448,0.968465,75.416667,24.69539,inf,inf
0,Unemployment,mlp,1349.70336,36.684176,4.42348,26.69181,0.494122,0.14909,0.96717,78.541667,27.591381,0.000256,0.420111
48,ausbee,mlpwk13,391.007244,19.673637,3.595159,15.493961,0.082525,0.167263,0.947901,91.190476,38.093646,inf,inf
35,ausbee,mlpkpssfalsep3,333.613995,18.258745,3.286238,14.214244,0.07167,0.146486,0.95491,94.761905,19.057366,inf,inf
27,ausbee,mlp,263.18521,16.210107,2.851759,12.132077,0.064744,0.1348,0.961435,94.761905,19.60374,0.000286,0.361878
75,austres,mlpwk13,330.661726,18.055612,0.08747,15.110663,0.111584,0.005208,0.998711,88.823529,24.907492,inf,inf
60,austres,mlpkpssfalsep1,315.009608,17.741231,0.086186,14.883686,0.102546,0.004923,0.998777,88.235294,23.57158,inf,inf
54,austres,mlp,316.706755,17.795568,0.074989,12.95803,0.107342,0.004952,0.99877,88.235294,8.936424,0.000225,0.234992
103,coloradoRiver,mlpwk13,0.249591,0.4982,95.448,0.311496,1.276697,0.8291,0.803147,65.675676,0.753442,inf,inf
89,coloradoRiver,mlpkpssfalsep2,0.231199,0.480615,89.132509,0.292405,1.162407,0.800656,0.812755,64.391892,0.694652,inf,inf
81,coloradoRiver,mlp,0.235417,0.485187,72.333855,0.259857,0.958569,0.736469,0.813605,63.243243,0.763438,0.000302,0.498848
133,gasoline,mlpwk15,67663.893667,259.9432,2.383199,214.756741,14.17632,1.47347,0.705833,42.95302,322.361197,inf,inf
116,gasoline,mlpkpssfalsep1,65268.167252,255.46571,2.33842,210.664789,17.327566,1.452588,0.713258,43.087248,319.831102,inf,inf
110,gasoline,mlp,61433.57555,247.857283,2.199466,196.399634,12.958859,1.302964,0.740158,40.134228,315.449839,0.000254,0.523039
160,heartrate,mlpwk15,0.607044,0.775486,0.728617,0.639888,0.283728,0.02047,0.994911,60.666667,0.61329,inf,inf
144,heartrate,mlpkpssfalsep2,7.250837,1.852792,1.578048,1.344454,2.09299,0.092892,0.96563,56.0,0.545248,inf,inf
137,heartrate,mlp,1.072802,1.02146,1.002817,0.868131,0.707717,0.03995,0.990517,54.666667,0.681373,0.000257,0.605355
187,milk,mlpwk14,834.597954,22.646144,2.082348,17.578888,0.478569,0.177903,0.943389,87.741935,20.518912,inf,inf
172,milk,mlpkpssfalsep2,247.878591,14.344669,1.279028,10.789984,0.183733,0.072213,0.98151,91.290323,17.115862,inf,inf
164,milk,mlp,36.575117,6.042718,0.583869,4.873061,0.033055,0.011123,0.997255,94.193548,7.569486,0.000678,0.468287
214,ozon,mlpwk13,1.94059,1.302547,25.240294,1.046808,0.603375,0.321131,0.90134,70.555556,1.904026,inf,inf
200,ozon,mlpkpssfalsep2,1.902311,1.276303,24.227526,1.014209,0.569571,0.313378,0.904513,80.0,1.065401,inf,inf
193,ozon,mlp,1.03109,1.015369,19.308518,0.818239,0.613578,0.245092,0.938248,71.944444,1.117851,0.000279,0.224784
242,pollution,mlpwk14,945644.097904,945.710735,25.646246,770.472233,0.439679,0.836909,0.72217,71.153846,1850.930134,inf,inf
227,pollution,mlpkpssfalsep2,518249.87759,719.690854,19.950049,589.606092,0.55714,1.026995,0.770623,71.538462,953.432658,inf,inf
220,pollution,mlp,541619.282335,735.711944,21.078495,607.614631,0.332088,0.695393,0.805884,70.769231,431.269911,0.000288,0.282004
269,redwine,mlpwk14,205473.883505,444.465713,16.449534,353.785616,0.667204,0.70054,0.841954,65.945946,556.595957,inf,inf
253,redwine,mlpkpssfalsep1,212482.090567,459.054658,15.979739,364.865304,1.192058,0.986146,0.810844,62.702703,282.73943,inf,inf
247,redwine,mlp,143403.090121,367.180201,13.265162,276.707918,0.369692,0.389581,0.902132,65.675676,237.434781,0.000268,1.016695
296,sunspot,mlpwk13,448.747171,21.107783,37.559837,15.780235,0.383333,0.199377,0.952653,74.912281,19.78346,inf,inf
281,sunspot,mlpkpssfalsep1,425.563047,20.549877,33.998428,15.071228,0.388018,0.187487,0.955324,80.877193,14.554581,inf,inf
274,sunspot,mlp,384.039361,19.595571,32.117264,14.324324,0.359634,0.170657,0.959721,81.578947,12.799614,0.00033,1.85332
324,temperature,mlpwk13,8.895282,2.97693,5.126143,2.405418,0.288469,0.118922,0.968333,74.166667,3.090635,inf,inf
311,temperature,mlpkpssfalsep3,6.874667,2.620456,4.611576,2.143725,0.265422,0.098525,0.97477,78.125,2.80033,inf,inf
303,temperature,mlp,5.494202,2.342424,4.111487,1.89343,0.267442,0.081361,0.979594,76.458333,2.62213,0.000274,0.728755
351,woolyrnq,mlpwk13,14938597.774537,2898.661156,34.996669,1667.947292,0.467432,0.969981,0.346882,56.956522,1353.394367,inf,inf
337,woolyrnq,mlpkpssfalsep2,997274.944355,932.776089,14.517046,685.521872,0.563135,0.832828,0.616118,67.826087,403.765643,inf,inf
330,woolyrnq,mlp,334464.080676,537.029952,8.345252,402.735047,0.374754,0.58421,0.811371,81.304348,378.942384,0.000286,0.921087