In [4]:
import pandas as pd
import matplotlib as plt
from metrics import metrics
from model import generics
pd.set_option('display.max_rows', 2000)

%load_ext autoreload
%autoreload 2

In [27]:
experiment_id = 'resudualens'

In [32]:
df_mean_metrics, df_all_metrics, df_prevs = metrics.open_fold_result(experiment_id)

In [33]:
df_mean_metrics.reset_index().sort_values(by=['ts', 'model'])#[df_mean_metrics.reset_index()['model'].str.contains("mlp-").values]
#usadas no artigo Airlines River Lake Milk Ozone Paper PollutionStar Sunspot Temperature

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
0,Unemployment,1aelmmean100,1.626016e+03,40.313380,5.064662,30.925771,0.311803,0.113898,0.971955,59.166667,25.385123,0.006368,0.099615
1,Unemployment,1am,1.355860e+03,36.821928,4.443740,27.018404,0.315899,0.090815,0.977188,70.833333,25.701975,0.000218,0.088543
2,Unemployment,1ammeanens,1.398706e+03,37.389332,4.613421,28.083908,0.289803,0.094403,0.976399,70.416667,21.864229,0.008975,1.404061
3,Unemployment,1ammeanenscdsrc0.1k1,3.160126e+03,55.031241,6.699511,41.976067,0.332451,0.180825,0.949783,67.500000,3.974068,inf,inf
4,Unemployment,1ammeanenscdsrc0.1k10,1.413231e+03,37.501989,4.722844,29.191034,0.286894,0.093949,0.976312,68.333333,3.924923,inf,inf
5,Unemployment,1ammeanenscdsrc0.1k20,1.322178e+03,36.323241,4.621360,28.286571,0.279032,0.089848,0.977625,69.583333,5.994745,inf,inf
6,Unemployment,1ammeanenscdsrc0.1k40,1.286794e+03,35.856536,4.569806,27.781147,0.278376,0.088113,0.978154,66.666667,9.683269,inf,inf
7,Unemployment,1ammeanenscdsrc0.1k5,1.583388e+03,39.633760,4.985304,30.794711,0.299391,0.101248,0.973986,68.750000,3.340422,inf,inf
8,Unemployment,1ammeanenscdsrc0.1k80,1.295939e+03,35.995082,4.559481,27.654568,0.277501,0.089035,0.977961,66.250000,16.873366,inf,inf
9,Unemployment,1ammeanenscdsrc0.5k1,1.794648e+03,41.778615,5.132822,31.825984,0.329510,0.120755,0.969502,67.916667,18.987859,inf,inf
10,Unemployment,1ammeanenscdsrc0.5k10,1.319183e+03,36.304585,4.409001,26.765456,0.310659,0.093315,0.977213,68.333333,17.883327,inf,inf
11,Unemployment,1ammeanenscdsrc0.5k20,1.313290e+03,36.226789,4.541972,27.601210,0.301370,0.091720,0.977453,66.666667,18.418548,inf,inf
12,Unemployment,1ammeanenscdsrc0.5k40,1.254789e+03,35.417244,4.491273,27.269232,0.280206,0.087012,0.978562,67.500000,18.885643,inf,inf
13,Unemployment,1ammeanenscdsrc0.5k5,1.331552e+03,36.442048,4.412918,26.752267,0.311707,0.093395,0.977100,71.250000,16.837964,inf,inf
14,Unemployment,1ammeanenscdsrc0.5k80,1.288866e+03,35.894417,4.518277,27.400545,0.273143,0.087866,0.978170,68.750000,20.209388,inf,inf
15,Unemployment,1ammeanenscdsrc0.8k1,1.518861e+03,38.699213,4.817136,29.471331,0.314458,0.105353,0.973931,69.583333,21.927988,inf,inf
16,Unemployment,1ammeanenscdsrc0.8k10,1.324499e+03,36.360995,4.361120,26.624963,0.315833,0.093575,0.977118,69.583333,20.585807,inf,inf
17,Unemployment,1ammeanenscdsrc0.8k20,1.321770e+03,36.331438,4.546481,27.704562,0.304532,0.093140,0.977203,69.166667,21.298909,inf,inf
18,Unemployment,1ammeanenscdsrc0.8k40,1.255475e+03,35.425032,4.503166,27.357445,0.276491,0.087172,0.978539,68.333333,20.669800,inf,inf
19,Unemployment,1ammeanenscdsrc0.8k5,1.398957e+03,37.290441,4.420009,27.030739,0.328433,0.099221,0.975752,68.333333,20.069675,inf,inf
20,Unemployment,1ammeanenscdsrc0.8k80,1.311097e+03,36.199546,4.510560,27.370004,0.277870,0.089232,0.977805,69.166667,20.801470,inf,inf
21,Unemployment,1ammedianens,1.305824e+03,36.121375,4.617833,28.031466,0.275123,0.088641,0.977915,70.833333,20.358281,0.009608,1.707698
22,Unemployment,1arima,3.367940e+03,58.033959,6.515261,42.026475,0.471769,0.210969,0.943804,70.833333,inf,inf,inf
23,Unemployment,1arimaeml,1.378775e+03,37.098745,4.488493,27.452054,0.319007,0.092573,0.976768,71.250000,25.177890,0.000101,0.012307
24,Unemployment,1as,1.322241e+03,36.362637,4.599497,28.307749,0.285973,0.089732,0.977632,66.666667,26.402280,0.000256,0.001933
25,Unemployment,1ascn,1.356866e+03,36.835659,4.405575,26.863987,0.326047,0.091826,0.977045,75.000000,23.447299,0.000452,0.153566
26,Unemployment,1asens,1.643765e+03,40.529123,4.862633,29.981828,0.326211,0.115321,0.971645,69.166667,29.002039,0.033951,0.115142
27,Unemployment,1db4mlp,2.746945e+03,52.410859,6.477787,41.123379,0.438655,0.159829,0.956334,67.500000,48.394770,0.000226,0.122170
28,Unemployment,1elm,1.195962e+03,34.578168,4.220603,25.797267,0.272980,0.081514,0.979738,65.416667,25.507882,0.000091,0.013658
29,Unemployment,1kanpert1,2.616089e+03,51.084969,5.986647,37.510680,0.790042,0.168653,0.956075,80.000000,30.553552,inf,inf
30,Unemployment,1kanpert2,2.450135e+03,49.466138,6.014296,37.785503,0.621742,0.141327,0.961335,77.083333,32.824190,inf,inf
31,Unemployment,1kanpert3,2.968244e+03,54.439171,6.747699,43.503929,0.667257,0.152687,0.955804,73.333333,34.697946,inf,inf
32,Unemployment,1kanval,1.382476e+03,37.180338,4.422418,27.142113,0.308116,0.084235,0.977824,75.000000,28.090327,inf,inf
33,Unemployment,1ma,2.001485e+04,141.473847,16.135910,106.854167,217.180415,3.553999,0.452619,37.500000,inf,inf,inf
34,Unemployment,1mlp,1.227733e+03,35.038242,4.194633,25.868907,0.285525,0.084710,0.979055,63.750000,25.933508,0.000297,0.288898
35,Unemployment,1nhitspert1,1.658421e+03,40.638045,4.955896,30.337116,0.371958,0.103452,0.973002,69.583333,28.867995,inf,inf
36,Unemployment,1nhitspert2,2.953364e+03,53.509264,7.009123,42.699454,0.470939,0.163381,0.954159,66.250000,37.013501,inf,inf
37,Unemployment,1nhitsval,1.441870e+03,37.954664,5.095459,30.278074,0.265587,0.089444,0.976680,64.166667,28.886534,inf,inf
38,Unemployment,1rw,4.504792e+03,67.117745,7.396214,46.958333,1.030982,0.289025,0.923308,79.166667,inf,inf,inf
39,Unemployment,1scn,1.240828e+03,35.174114,4.324946,26.143831,0.279704,0.085231,0.978887,64.583333,25.345879,0.000808,0.098588
40,Unemployment,1svr,1.056385e+03,32.502073,4.101036,24.105751,0.238184,0.074374,0.981888,66.666667,22.476597,0.000589,0.015608
41,ausbee,1aelmmean100,2.624062e+02,16.197683,2.947685,12.343182,0.101879,0.189699,0.944962,95.238095,14.714511,0.005083,0.079099
42,ausbee,1am,2.571279e+02,16.033896,2.685414,11.187198,0.094734,0.176233,0.947829,95.238095,14.894268,0.000199,0.053449
43,ausbee,1ammeanens,2.558799e+02,15.995580,2.878756,12.028548,0.100640,0.188142,0.945952,95.238095,14.731597,0.006803,0.291890
44,ausbee,1ammeanenscdsrc0.1k1,4.856461e+02,20.980700,3.645695,15.240060,0.159037,0.306396,0.904636,91.904762,6.225454,inf,inf
45,ausbee,1ammeanenscdsrc0.1k10,2.629332e+02,16.208479,2.914769,12.230348,0.105136,0.199436,0.943524,95.238095,8.454343,inf,inf
46,ausbee,1ammeanenscdsrc0.1k20,2.521232e+02,15.873052,2.845621,11.936409,0.100823,0.191394,0.945913,95.238095,9.708119,inf,inf
47,ausbee,1ammeanenscdsrc0.1k40,2.508722e+02,15.835699,2.842779,11.902211,0.100328,0.189585,0.946306,95.238095,11.239826,inf,inf
48,ausbee,1ammeanenscdsrc0.1k5,2.783764e+02,16.673416,3.008520,12.636523,0.110731,0.210656,0.940121,95.238095,7.398416,inf,inf
49,ausbee,1ammeanenscdsrc0.1k80,2.541786e+02,15.941692,2.865643,11.978197,0.100452,0.188292,0.946128,95.238095,13.482249,inf,inf
50,ausbee,1ammeanenscdsrc0.5k1,2.595768e+02,16.011378,2.753888,11.642718,0.099618,0.192787,0.944902,94.761905,11.545455,inf,inf
51,ausbee,1ammeanenscdsrc0.5k10,2.462782e+02,15.686477,2.753607,11.582496,0.097236,0.183995,0.947642,95.238095,11.754010,inf,inf
52,ausbee,1ammeanenscdsrc0.5k20,2.458163e+02,15.669916,2.758771,11.568624,0.097554,0.183713,0.947720,95.238095,12.374656,inf,inf
53,ausbee,1ammeanenscdsrc0.5k40,2.446689e+02,15.639301,2.759859,11.544577,0.097164,0.182663,0.948011,95.238095,13.059408,inf,inf
54,ausbee,1ammeanenscdsrc0.5k5,2.493038e+02,15.774786,2.721989,11.464272,0.097136,0.185734,0.947034,95.238095,11.347141,inf,inf
55,ausbee,1ammeanenscdsrc0.5k80,2.517599e+02,15.866110,2.828430,11.818775,0.099417,0.186228,0.946693,95.238095,14.186394,inf,inf
56,ausbee,1ammeanenscdsrc0.8k1,2.564815e+02,15.950176,2.795935,11.803536,0.095644,0.185170,0.946414,94.761905,11.935319,inf,inf
57,ausbee,1ammeanenscdsrc0.8k10,2.408426e+02,15.504357,2.722632,11.423136,0.092612,0.175836,0.949504,95.238095,12.155819,inf,inf
58,ausbee,1ammeanenscdsrc0.8k20,2.409354e+02,15.514747,2.745393,11.503310,0.094027,0.177594,0.949214,95.238095,12.527519,inf,inf
59,ausbee,1ammeanenscdsrc0.8k40,2.440216e+02,15.616735,2.783985,11.645324,0.095575,0.179888,0.948525,95.238095,13.183508,inf,inf
60,ausbee,1ammeanenscdsrc0.8k5,2.454148e+02,15.639062,2.720698,11.434642,0.093139,0.178025,0.948653,95.238095,11.830930,inf,inf
61,ausbee,1ammeanenscdsrc0.8k80,2.518016e+02,15.867404,2.841407,11.870836,0.098750,0.185106,0.946873,95.238095,14.214483,inf,inf
62,ausbee,1ammedianens,2.548846e+02,15.963041,2.810513,11.736728,0.099104,0.184543,0.946638,95.238095,14.754529,0.009989,0.885822
63,ausbee,1arima,2.751478e+02,16.587580,3.128794,13.102531,0.111015,0.210175,0.940390,95.238095,inf,inf,inf
64,ausbee,1arimaeml,2.588200e+02,16.086344,2.712961,11.318852,0.094608,0.175019,0.947815,95.238095,15.006228,0.000097,0.010514
65,ausbee,1as,2.841879e+02,16.857873,2.857842,11.813287,0.102074,0.188851,0.943145,95.238095,14.745258,0.000314,0.001640
66,ausbee,1ascn,2.525587e+02,15.892095,2.636745,10.985941,0.092197,0.171355,0.949068,95.238095,14.868763,0.000467,0.126225
67,ausbee,1asens,2.653443e+02,16.289231,3.084943,12.927774,0.106088,0.201373,0.942806,95.238095,14.383242,0.040085,0.057557
68,ausbee,1db4mlp,2.366413e+03,48.645780,9.883100,43.036219,1.023045,1.972288,0.314801,47.619048,65.195196,0.000217,0.133767
69,ausbee,1elm,2.460521e+02,15.682530,2.829254,11.873042,0.083119,0.160410,0.951537,95.238095,15.827530,0.000101,0.018074
70,ausbee,1kanpert1,2.418339e+02,15.534693,2.616152,11.225557,0.067739,0.143363,0.955125,95.238095,15.553369,inf,inf
71,ausbee,1kanpert2,2.779875e+02,16.667515,3.026636,12.784561,0.079337,0.160443,0.948942,95.238095,16.516117,inf,inf
72,ausbee,1kanpert3,3.588001e+02,18.917845,3.356838,14.187066,0.097819,0.193686,0.936038,95.238095,17.983179,inf,inf
73,ausbee,1kanval,3.010840e+02,17.350047,3.077601,13.161542,0.082681,0.181179,0.943101,95.238095,19.759605,inf,inf
74,ausbee,1ma,1.122846e+03,33.508892,6.705425,28.592857,1092.667400,22.569804,0.257345,66.666667,inf,inf,inf
75,ausbee,1mlp,2.565738e+02,16.014606,2.624605,11.001652,0.084952,0.169981,0.948854,95.238095,15.473586,0.000267,0.348765
76,ausbee,1nhitspert1,3.018578e+02,17.316660,2.964832,12.515090,0.101094,0.202719,0.938866,93.333333,19.782273,inf,inf
77,ausbee,1nhitspert2,4.189929e+02,20.372504,3.831390,16.174229,0.140630,0.273792,0.914934,90.476190,22.978865,inf,inf
78,ausbee,1nhitsval,3.106737e+02,17.607162,3.138920,13.326526,0.088227,0.185451,0.941460,93.809524,19.682432,inf,inf
79,ausbee,1rw,2.369238e+03,48.674820,9.924549,43.142857,1.008105,1.955651,0.308045,47.619048,inf,inf,inf
80,ausbee,1scn,2.904620e+02,16.973547,2.936450,12.442672,0.088173,0.174966,0.945137,95.238095,16.599127,0.000598,0.090703
81,ausbee,1svr,3.359869e+02,18.329944,3.422244,14.468123,0.104916,0.204601,0.935664,95.238095,15.155091,0.000617,0.016603
82,austres,1aelmmean100,6.209803e+02,24.414280,0.110461,19.330640,0.220630,0.058550,0.984557,77.500000,21.653524,0.005588,0.093457
83,austres,1am,2.943825e+03,54.256461,0.290670,50.903803,1.191499,0.236479,0.929875,87.500000,52.059218,0.000197,0.015733
84,austres,1ammeanens,3.593127e+02,18.955540,0.078604,13.749585,0.129850,0.034995,0.990972,75.000000,17.077603,0.007532,0.121622
85,austres,1ammeanenscdsrc0.1k1,3.684795e+02,19.191984,0.082147,14.366953,0.133128,0.035853,0.990747,75.000000,17.269814,inf,inf
86,austres,1ammeanenscdsrc0.1k10,3.589407e+02,18.945566,0.078720,13.769569,0.129675,0.034957,0.990982,75.000000,17.070934,inf,inf
87,austres,1ammeanenscdsrc0.1k20,3.592807e+02,18.954649,0.078565,13.742812,0.129840,0.034992,0.990973,75.000000,17.093877,inf,inf
88,austres,1ammeanenscdsrc0.1k40,3.596195e+02,18.963611,0.078687,13.764202,0.129944,0.035023,0.990965,75.000000,17.108238,inf,inf
89,austres,1ammeanenscdsrc0.1k5,3.614052e+02,19.009785,0.079617,13.926337,0.130778,0.035204,0.990919,75.000000,17.160994,inf,inf
90,austres,1ammeanenscdsrc0.1k80,3.591199e+02,18.950444,0.078528,13.736335,0.129800,0.034978,0.990977,75.000000,17.089065,inf,inf
91,austres,1ammeanenscdsrc0.5k1,3.479177e+02,18.652490,0.078482,13.724145,0.128799,0.034143,0.991227,75.000000,16.849029,inf,inf
92,austres,1ammeanenscdsrc0.5k10,3.517113e+02,18.753892,0.078931,13.801450,0.128924,0.034409,0.991145,75.000000,17.004099,inf,inf
93,austres,1ammeanenscdsrc0.5k20,3.516993e+02,18.753633,0.078563,13.738231,0.128598,0.034384,0.991148,75.000000,17.017364,inf,inf
94,austres,1ammeanenscdsrc0.5k40,3.529104e+02,18.785906,0.078163,13.669754,0.128570,0.034465,0.991122,75.000000,17.021415,inf,inf
95,austres,1ammeanenscdsrc0.5k5,3.500846e+02,18.710480,0.078619,13.747475,0.128699,0.034282,0.991182,75.000000,16.930539,inf,inf
96,austres,1ammeanenscdsrc0.5k80,3.562503e+02,18.874594,0.077841,13.615523,0.129099,0.034732,0.991045,75.000000,17.063319,inf,inf
97,austres,1ammeanenscdsrc0.8k1,3.476442e+02,18.645167,0.078523,13.731637,0.128883,0.034131,0.991232,75.000000,16.730118,inf,inf
98,austres,1ammeanenscdsrc0.8k10,3.500929e+02,18.710752,0.078267,13.687771,0.128707,0.034283,0.991181,75.000000,16.791274,inf,inf
99,austres,1ammeanenscdsrc0.8k20,3.514974e+02,18.748252,0.078128,13.663715,0.128616,0.034372,0.991152,75.000000,16.807401,inf,inf
100,austres,1ammeanenscdsrc0.8k40,3.533371e+02,18.797257,0.078013,13.644251,0.128721,0.034505,0.991111,75.000000,16.864552,inf,inf
101,austres,1ammeanenscdsrc0.8k5,3.491917e+02,18.686645,0.078396,13.710264,0.128900,0.034236,0.991199,75.000000,16.796205,inf,inf
102,austres,1ammeanenscdsrc0.8k80,3.565128e+02,18.881545,0.077853,13.617730,0.129181,0.034756,0.991039,75.000000,16.985268,inf,inf
103,austres,1ammedianens,3.591926e+02,18.952358,0.078584,13.746231,0.129805,0.034980,0.990976,75.000000,17.062101,0.008884,0.138278
104,austres,1arima,3.581316e+02,18.924365,0.078380,13.710330,0.129713,0.034904,0.990999,75.000000,inf,inf,inf
105,austres,1arimaeml,3.753378e+04,168.559005,0.878572,153.756870,2.375782,0.675232,0.664725,60.000000,134.854874,0.000081,0.004666
106,austres,1as,3.832384e+02,19.576477,0.090181,15.761930,0.149014,0.038063,0.990280,87.500000,17.359958,0.000174,0.000453
107,austres,1ascn,3.578912e+02,18.918011,0.078309,13.697853,0.129659,0.034884,0.991005,75.000000,17.053746,0.000494,0.062208
108,austres,1asens,3.558086e+02,18.862801,0.081626,14.267643,0.134065,0.035070,0.991012,75.000000,16.675508,0.043428,0.065000
109,austres,1db4mlp,4.237378e+01,6.509301,0.031972,5.600173,0.024789,0.004530,0.998893,87.500000,10.700594,0.000555,0.063688
110,austres,1elm,3.302518e+02,18.078528,0.076234,13.336019,0.132551,0.034072,0.991466,80.000000,17.368624,0.000076,0.012021
111,austres,1kanpert1,2.138074e+02,14.622143,0.063736,11.175220,0.086178,0.020623,0.994674,87.500000,21.305822,inf,inf
112,austres,1kanpert2,5.349860e+02,23.129764,0.116617,20.424852,0.146359,0.044370,0.987617,75.000000,34.693322,inf,inf
113,austres,1kanpert3,1.474650e+03,38.401168,0.197532,34.576480,0.221993,0.103554,0.968376,75.000000,58.991860,inf,inf
114,austres,1kanval,3.348874e+02,18.293993,0.073194,12.799613,0.141922,0.037313,0.991007,75.000000,16.604929,inf,inf
115,austres,1ma,2.263914e+03,47.580603,0.263919,46.187500,1.069906,0.175465,0.947816,87.500000,inf,inf,inf
116,austres,1mlp,3.984211e+02,19.957359,0.083277,14.567205,0.154979,0.042526,0.989517,75.000000,16.861987,0.000237,0.336752
117,austres,1nhitspert1,2.140558e+02,14.630643,0.063736,11.175366,0.086278,0.020647,0.994668,87.500000,21.305856,inf,inf
118,austres,1nhitspert2,5.347740e+02,23.125180,0.116620,20.425171,0.146300,0.044353,0.987622,75.000000,34.692123,inf,inf
119,austres,1nhitsval,3.969834e+02,19.879966,0.086889,15.208446,0.160917,0.042834,0.989488,76.250000,18.338823,inf,inf
120,austres,1rw,2.263914e+03,47.580603,0.263919,46.187500,1.069906,0.175465,0.947816,87.500000,inf,inf,inf
121,austres,1scn,2.526704e+02,15.766243,0.072437,12.675292,0.114763,0.026097,0.993481,86.250000,16.469120,0.000495,0.037014
122,austres,1svr,3.581322e+02,18.924382,0.080876,14.142564,0.145121,0.037690,0.990642,87.500000,16.838591,0.000377,0.001549
123,coloradoRiver,1aelmmean100,1.104801e-01,0.332367,29.115517,0.266891,0.727696,0.698260,0.662504,56.081081,0.678480,0.008155,0.103429
124,coloradoRiver,1am,1.054103e-01,0.324668,28.735633,0.263108,0.734753,0.697479,0.670043,55.540541,0.677055,0.000237,0.376771
125,coloradoRiver,1ammeanens,1.106225e-01,0.332592,29.365952,0.269544,0.755204,0.699405,0.663611,54.729730,0.680525,0.016209,0.215428
126,coloradoRiver,1ammeanenscdsrc0.1k1,1.648933e-01,0.405577,33.787278,0.308979,0.687462,0.746689,0.588801,52.027027,0.564627,inf,inf
127,coloradoRiver,1ammeanenscdsrc0.1k10,1.363888e-01,0.369232,31.718376,0.291546,0.720174,0.717481,0.627059,55.405405,0.589842,inf,inf
128,coloradoRiver,1ammeanenscdsrc0.1k20,1.303064e-01,0.360942,31.248581,0.287340,0.729259,0.713389,0.635298,55.270270,0.607965,inf,inf
129,coloradoRiver,1ammeanenscdsrc0.1k40,1.232389e-01,0.351033,30.644679,0.281554,0.738430,0.707279,0.645181,55.270270,0.631686,inf,inf
130,coloradoRiver,1ammeanenscdsrc0.1k5,1.441213e-01,0.379489,32.320112,0.296886,0.714918,0.724730,0.616802,54.729730,0.574577,inf,inf
131,coloradoRiver,1ammeanenscdsrc0.1k80,1.151922e-01,0.339392,29.862150,0.274371,0.751594,0.702950,0.656905,54.324324,0.661332,inf,inf
132,coloradoRiver,1ammeanenscdsrc0.5k1,7.846971e-02,0.279601,23.977004,0.212362,0.616801,0.701014,0.697570,61.081081,0.626038,inf,inf
133,coloradoRiver,1ammeanenscdsrc0.5k10,8.256492e-02,0.287076,24.451183,0.221317,0.637061,0.674758,0.702544,61.756757,0.628387,inf,inf
134,coloradoRiver,1ammeanenscdsrc0.5k20,8.815966e-02,0.296785,25.509996,0.231996,0.661988,0.679773,0.693975,61.756757,0.640189,inf,inf
135,coloradoRiver,1ammeanenscdsrc0.5k40,9.455129e-02,0.307447,26.706906,0.243927,0.690065,0.686191,0.684051,60.405405,0.652024,inf,inf
136,coloradoRiver,1ammeanenscdsrc0.5k5,7.938657e-02,0.281216,23.935704,0.215192,0.621472,0.666598,0.708387,62.567568,0.625007,inf,inf
137,coloradoRiver,1ammeanenscdsrc0.5k80,1.040175e-01,0.322506,28.365445,0.260057,0.732787,0.693622,0.672166,55.675676,0.669445,inf,inf
138,coloradoRiver,1ammeanenscdsrc0.8k1,8.300026e-02,0.287746,25.198984,0.223684,0.677587,0.665880,0.703335,61.756757,0.647865,inf,inf
139,coloradoRiver,1ammeanenscdsrc0.8k10,8.255591e-02,0.287077,24.902795,0.225342,0.643504,0.659813,0.707683,63.378378,0.643318,inf,inf
140,coloradoRiver,1ammeanenscdsrc0.8k20,8.869316e-02,0.297719,25.968460,0.236283,0.676402,0.667241,0.697292,61.891892,0.652397,inf,inf
141,coloradoRiver,1ammeanenscdsrc0.8k40,9.490378e-02,0.308023,27.064714,0.247061,0.704398,0.678855,0.686106,60.405405,0.660848,inf,inf
142,coloradoRiver,1ammeanenscdsrc0.8k5,8.070961e-02,0.283818,24.551129,0.220816,0.636717,0.657788,0.709361,62.972973,0.640807,inf,inf
143,coloradoRiver,1ammeanenscdsrc0.8k80,1.038996e-01,0.322323,28.445459,0.260714,0.736836,0.691127,0.673236,55.945946,0.673401,inf,inf
144,coloradoRiver,1ammedianens,1.102603e-01,0.332046,29.437637,0.270196,0.761820,0.697966,0.664662,54.594595,0.682969,0.011062,0.204301
145,coloradoRiver,1arima,1.067550e-01,0.326734,29.063906,0.266386,0.750629,0.697794,0.666893,51.351351,inf,inf,inf
146,coloradoRiver,1arimaeml,1.123403e-01,0.335147,29.667460,0.271047,0.738770,0.695980,0.661844,56.621622,0.681797,0.000118,0.006135
147,coloradoRiver,1as,1.157236e-01,0.340182,31.208702,0.281705,0.769452,0.672576,0.669733,66.216216,0.690284,0.000518,0.006001
148,coloradoRiver,1ascn,1.134179e-01,0.336776,29.786746,0.273080,0.757200,0.700139,0.661337,58.108108,0.678334,0.000608,0.852146
149,coloradoRiver,1asens,1.155766e-01,0.339938,31.092221,0.282133,0.814558,0.684785,0.665591,61.621622,0.683395,0.031711,0.101847
150,coloradoRiver,1db4mlp,3.935963e-02,0.198387,18.592826,0.153850,1.002394,0.894125,0.750153,53.783784,0.693251,0.000283,0.524851
151,coloradoRiver,1elm,1.956297e-02,0.139332,14.552774,0.112234,0.843732,0.571025,0.864863,70.135135,0.689594,0.000111,0.020545
152,coloradoRiver,1kanpert1,2.472727e-02,0.157227,16.080312,0.130105,0.814701,0.560322,0.843462,61.891892,0.674860,inf,inf
153,coloradoRiver,1kanpert2,2.915981e-02,0.170726,17.988973,0.142278,0.884429,0.584477,0.823847,60.675676,0.675658,inf,inf
154,coloradoRiver,1kanpert3,3.778987e-02,0.194353,20.579307,0.160585,1.023701,0.647707,0.785060,60.405405,0.696524,inf,inf
155,coloradoRiver,1kanval,2.882195e-02,0.169643,16.463104,0.133258,0.908544,0.724982,0.813257,55.000000,0.696035,inf,inf

In [5]:
metric = 'RMSE'

proposed_list = []
for k, df in df_mean_metrics.reset_index().groupby('ts'):
    #arima = df[df['model'] == 'arima'][metric].iloc[0]
    #svr = df[df['model'] == 'arima'][metric].iloc[0]
    #mlp = df[df['model'] == 'arima'][metric].iloc[0]

    #df_arima[k] = (df.set_index('model')[metric] < arima)
    #df_svr[k] = (df.set_index('model')[metric] < svr)
    #df_mlp[k] = (df.set_index('model')[metric] < mlp)

    svr_proposed = df[( (df['model'].str.contains("1ammeanenscdsrc12k10")))].copy()
    if svr_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(svr_proposed.iloc[svr_proposed['val_metric'].argmin()]).T)

    mlp_proposed = df[( (df['model'].str.contains("mlpkpssfalsep")) )].copy()
    if mlp_proposed.shape[0]>0:
        proposed_list.append(pd.DataFrame(mlp_proposed.iloc[mlp_proposed['val_metric'].argmin()]).T)

    proposed_list.append(
        df[df['model'].isin(
            [ '1svr', '1arima', '1arimamlp', '1amens', '1asens', '1as', '1am']
        )]
    )

In [6]:
pd.concat(proposed_list)

,ts,model,MSE,RMSE,MAPE,MAE,theil,ARV,IA,POCID,val_metric,time_testing,time_training
3,Unemployment,1ammeanenscdsrc12k10,1319.182521,36.304585,4.409001,26.765456,0.310659,0.093315,0.977213,68.333333,17.883327,inf,inf
0,Unemployment,1am,1355.859735,36.821928,4.44374,27.018404,0.315899,0.090815,0.977188,70.833333,25.701975,0.000218,0.088543
21,Unemployment,1arima,3367.940389,58.033959,6.515261,42.026475,0.471769,0.210969,0.943804,70.833333,inf,inf,inf
23,Unemployment,1as,1322.241377,36.362637,4.599497,28.307749,0.285973,0.089732,0.977632,66.666667,26.40228,0.000256,0.001933
25,Unemployment,1asens,1643.764815,40.529123,4.862633,29.981828,0.326211,0.115321,0.971645,69.166667,29.002039,0.033951,0.115142
39,Unemployment,1svr,1056.384751,32.502073,4.101036,24.105751,0.238184,0.074374,0.981888,66.666667,22.476597,0.000589,0.015608
40,ausbee,1am,257.127874,16.033896,2.685414,11.187198,0.094734,0.176233,0.947829,95.238095,14.894268,0.000199,0.053449
61,ausbee,1arima,275.147801,16.58758,3.128794,13.102531,0.111015,0.210175,0.94039,95.238095,inf,inf,inf
63,ausbee,1as,284.187885,16.857873,2.857842,11.813287,0.102074,0.188851,0.943145,95.238095,14.745258,0.000314,0.00164
65,ausbee,1asens,265.344329,16.289231,3.084943,12.927774,0.106088,0.201373,0.942806,95.238095,14.383242,0.040085,0.057557
79,ausbee,1svr,335.986862,18.329944,3.422244,14.468123,0.104916,0.204601,0.935664,95.238095,15.155091,0.000617,0.016603
80,austres,1am,2943.82501,54.256461,0.29067,50.903803,1.191499,0.236479,0.929875,87.5,52.059218,0.000197,0.015733
101,austres,1arima,358.131609,18.924365,0.07838,13.71033,0.129713,0.034904,0.990999,75.0,inf,inf,inf
103,austres,1as,383.238441,19.576477,0.090181,15.76193,0.149014,0.038063,0.99028,87.5,17.359958,0.000174,0.000453
105,austres,1asens,355.808593,18.862801,0.081626,14.267643,0.134065,0.03507,0.991012,75.0,16.675508,0.043428,0.065
119,austres,1svr,358.132239,18.924382,0.080876,14.142564,0.145121,0.03769,0.990642,87.5,16.838591,0.000377,0.001549
120,coloradoRiver,1am,0.10541,0.324668,28.735633,0.263108,0.734753,0.697479,0.670043,55.540541,0.677055,0.000237,0.376771
141,coloradoRiver,1arima,0.106755,0.326734,29.063906,0.266386,0.750629,0.697794,0.666893,51.351351,inf,inf,inf
143,coloradoRiver,1as,0.115724,0.340182,31.208702,0.281705,0.769452,0.672576,0.669733,66.216216,0.690284,0.000518,0.006001
145,coloradoRiver,1asens,0.115577,0.339938,31.092221,0.282133,0.814558,0.684785,0.665591,61.621622,0.683395,0.031711,0.101847
159,coloradoRiver,1svr,0.016735,0.129364,12.780709,0.103989,0.990695,0.654656,0.870977,70.27027,0.674405,0.001814,0.032213
160,consumocoformated,1arima,11895.939043,109.068506,2.431796,90.197184,1.347885,0.245301,0.941487,69.230769,inf,inf,inf
163,gasoline,1am,41498.44815,203.708827,1.80896,162.747992,11.179156,1.182677,0.758772,44.189189,281.914516,0.000193,0.140035
184,gasoline,1arima,40242.333248,200.604918,1.818217,163.78739,15.868613,1.149002,0.765986,43.243243,inf,inf,inf
186,gasoline,1as,40758.441695,201.8872,1.779735,160.070815,9.542606,1.234185,0.758475,41.891892,279.941234,0.001706,0.013284
188,gasoline,1asens,40395.251865,200.985286,1.793751,161.345428,15.032615,1.207525,0.761373,43.783784,281.756485,0.040336,0.106698
202,gasoline,1svr,45969.039234,214.403916,1.889711,170.366131,8.641945,1.304089,0.731922,43.243243,284.499112,0.001248,0.300313
206,heartrate,1ammeanenscdsrc12k10,0.219027,0.467958,0.521918,0.437374,0.238831,0.087706,0.975075,26.666667,0.706541,inf,inf
203,heartrate,1am,0.29125,0.539675,0.5459,0.458011,0.328852,0.113878,0.967038,26.666667,0.762095,0.000205,0.05271
224,heartrate,1arima,0.266216,0.515961,0.555209,0.465495,0.277636,0.104168,0.969943,26.666667,inf,inf,inf
226,heartrate,1as,0.259021,0.508941,0.571822,0.479014,0.24292,0.1015,0.970755,26.666667,0.741076,0.000247,0.001066
228,heartrate,1asens,0.262833,0.512613,0.563065,0.471732,0.259076,0.103905,0.970162,26.666667,0.729999,0.024997,0.103449
242,heartrate,1svr,6.553573,2.559995,2.819059,2.33956,33.278475,1.133331,0.535772,26.666667,1.010793,0.000535,0.020482
243,irradiancefloripa,1am,238939.700775,488.813952,156.750259,358.908672,0.593603,0.194843,0.952549,71.136842,516.393701,0.009016,1.23517
264,irradiancefloripa,1arima,244303.125986,494.270296,159.898192,366.526323,0.581583,0.191482,0.952344,72.210526,inf,inf,inf
266,irradiancefloripa,1as,241784.46954,491.715842,164.771698,370.894386,0.651422,0.201965,0.951362,72.210526,511.544042,0.005862,0.096955
281,irradiancefloripa,1svr,238193.109988,488.050315,104.246962,336.337601,0.537605,0.190657,0.953201,72.0,510.216998,0.126248,3.435419
282,irradiancefortaleza,1am,53343.007271,230.960869,49.272878,172.301063,0.247613,0.066861,0.983613,87.094737,241.627912,0.003683,1.081217
303,irradiancefortaleza,1arima,61551.633395,248.096016,55.7475,188.985538,0.279591,0.07756,0.980999,87.789474,inf,inf,inf
305,irradiancefortaleza,1as,52115.676432,228.288581,49.516173,168.42998,0.232357,0.064082,0.984148,87.368421,242.198181,0.047588,0.3959
307,irradiancefortaleza,1asens,55403.968988,235.380314,52.350894,177.878271,0.253869,0.069139,0.983007,86.505263,243.725425,0.105783,1.019811
321,irradiancefortaleza,1svr,49549.05768,222.596176,46.658491,155.490482,0.219199,0.061224,0.984903,85.052632,237.965153,0.075294,0.867297
323,irradiancesalvador,1am,251854.862642,501.849912,70.241283,367.460858,0.487644,0.168046,0.957937,78.8,544.455893,0.003766,1.897281
344,irradiancesalvador,1arima,365088.565872,604.225592,92.884777,462.077816,0.50706,0.194226,0.945134,76.421053,inf,inf,inf
346,irradiancesalvador,1as,232506.50559,482.189284,56.454017,344.090319,0.434162,0.152425,0.96162,78.947368,523.814859,0.05237,0.450396
348,irradiancesalvador,1asens,248254.092653,498.246717,59.69179,353.452049,0.424819,0.154304,0.960033,78.042105,539.226648,0.484138,23.356557
363,irradiancesalvador,1svr,212621.631281,461.109132,34.823105,301.679435,0.429404,0.138999,0.965113,80.631579,481.924745,0.24792,5.975839
365,irradiancesp,1am,867990.331473,931.658681,inf,623.50882,1.607872,1.06814,0.789901,65.136842,979.016885,0.003551,0.837829
386,irradiancesp,1arima,876743.013333,936.345563,inf,625.448836,1.723652,1.094501,0.787111,62.736842,inf,inf,inf
388,irradiancesp,1as,859170.819989,926.914678,inf,612.70201,1.391476,1.019522,0.796792,63.789474,979.785537,0.006559,0.093645
403,irradiancesp,1svr,806930.024275,898.292839,inf,580.027933,1.23492,0.810297,0.821906,66.315789,948.943833,0.027569,0.383906
404,melbmin,1am,5.137975,2.26671,18.158844,1.7439,2.162593,0.528854,0.886435,43.835616,2.145489,0.000355,0.613982
425,melbmin,1arima,5.10482,2.259385,18.1681,1.739152,2.134016,0.523,0.887529,43.835616,inf,inf,inf
427,melbmin,1as,5.180884,2.276156,18.235516,1.751092,2.116245,0.533627,0.885303,42.739726,2.128627,0.014369,0.146498
429,melbmin,1asens,5.233691,2.287724,18.319495,1.753294,2.125835,0.538067,0.88427,43.534247,2.126723,0.189045,10.359528
442,melbmin,1svr,5.076043,2.253008,17.958814,1.741966,2.121064,0.498284,0.890223,43.287671,2.146753,0.0131,0.131098
446,milk,1ammeanenscdsrc12k10,29.073932,5.385342,0.523695,4.365165,0.034251,0.00821,0.997989,93.333333,5.314159,inf,inf
443,milk,1am,21.504762,4.527524,0.426904,3.551866,0.02491,0.006349,0.998481,93.333333,7.339537,0.000215,0.106153
464,milk,1arima,18.340326,4.282561,0.395625,3.31528,0.021327,0.005282,0.99872,93.333333,inf,inf,inf
466,milk,1as,19.809,4.45073,0.409336,3.387781,0.022419,0.005513,0.998641,93.333333,6.08447,0.000278,0.003551
468,milk,1asens,20.779985,4.557273,0.406763,3.378924,0.023984,0.005886,0.998561,93.333333,6.264871,0.034873,0.094055
482,milk,1svr,21.465772,4.633117,0.475202,3.962725,0.024398,0.005955,0.998529,93.333333,6.712026,0.000496,0.002488
483,ozon,1am,1.192335,1.091939,19.845625,0.907138,0.681594,0.327465,0.936201,83.333333,0.952664,0.000211,0.040698
504,ozon,1arima,1.243089,1.114939,17.181052,0.863563,0.864499,0.331024,0.934331,83.333333,inf,inf,inf
506,ozon,1as,1.530417,1.2371,20.603941,0.959387,0.685917,0.35364,0.922609,83.333333,0.816181,0.00027,0.003339
508,ozon,1asens,1.528759,1.235985,21.325465,1.003493,0.706357,0.361198,0.921848,80.0,0.82155,0.025611,0.227374
522,ozon,1svr,2.557373,1.599179,24.0276,1.142297,0.883162,0.677024,0.860362,77.777778,0.809358,0.000556,0.034371
523,pollution,1am,782119.957089,884.37276,27.407842,726.431789,0.335503,0.662758,0.742271,69.230769,611.579003,0.000219,0.088035
544,pollution,1arima,801434.609458,895.228803,29.420365,742.29676,0.924405,1.472344,0.544834,69.230769,inf,inf,inf
546,pollution,1as,696239.427855,834.409628,24.778128,680.372908,0.508829,0.814202,0.707646,69.230769,561.056658,0.000288,0.002863
548,pollution,1asens,1026584.842765,1011.349669,31.08504,832.458807,0.516404,0.728751,0.685342,65.384615,548.0143,0.024275,0.096561
562,pollution,1svr,2588859.03668,1608.993175,43.257618,1273.059171,0.577857,0.829877,0.510933,38.461538,475.907989,0.00045,0.018178
563,recifeaccday,1am,48.856848,6.989767,21.181601,5.104328,1.166682,1.037078,0.805433,57.724551,7.666879,0.000318,0.633721
584,recifeaccday,1arima,49.01301,7.000929,21.596595,5.125169,1.233839,1.117764,0.80002,57.48503,inf,inf,inf
586,recifeaccday,1as,48.831646,6.987964,21.236137,5.148999,1.079445,1.018989,0.807414,59.281437,7.624622,0.004306,0.050436
588,recifeaccday,1asens,48.079466,6.933933,21.369393,5.080513,1.173623,1.07922,0.805032,59.221557,7.527558,0.079944,0.340178
604,recifeaccday,1svr,63.773028,7.985802,25.308427,6.14739,2.723418,1.876641,0.705194,55.08982,8.560863,0.009128,0.14824
606,redwine,1am,91941.519121,303.218363,9.085946,236.42244,0.33126,0.324273,0.929216,72.222222,332.951287,0.000133,0.08128
627,redwine,1arima,84740.60381,291.102394,9.927254,250.67493,0.2851,0.258761,0.939158,72.222222,inf,inf,inf
629,redwine,1as,194950.148692,441.531594,13.975622,347.337534,0.393535,0.378715,0.882845,66.666667,316.487319,0.000284,0.012136
631,redwine,1asens,113667.072048,336.986829,10.09575,260.958669,0.336599,0.285657,0.924612,75.555556,317.54953,0.027756,0.118082
645,redwine,1svr,119421.811701,345.574611,11.678677,273.878046,0.18635,0.214611,0.934846,83.333333,293.966196,0.000405,0.003408
646,samurec,1am,49.203962,7.014553,20.229102,5.822893,31.989155,32.063554,0.194022,57.711864,7.381227,0.000253,0.356422
667,samurec,1arima,48.486224,6.963205,20.58667,5.859533,28.396645,34.597902,0.193332,64.40678,inf,inf,inf
668,samurec,1as,51.162256,7.15278,20.348512,5.894498,18.947475,19.645881,0.216854,52.542373,7.375393,0.001513,0.016475
681,samurec,1svr,60.667759,7.788951,22.478134,6.483429,13.486341,6.112231,0.30415,44.915254,7.089395,0.002315,0.564496
682,sunspot,1am,363.782376,19.073071,40.752607,15.840357,0.33369,0.204088,0.950094,60.714286,22.703003,0.0002,0.088501
703,sunspot,1arima,365.478743,19.117498,36.503109,15.719171,0.346894,0.193887,0.951367,67.857143,inf,inf,inf
705,sunspot,1as,371.412243,19.272059,42.700058,16.149458,0.335396,0.208146,0.949048,60.714286,22.11922,0.000284,0.002381
707,sunspot,1asens,358.720251,18.939693,39.453506,15.682219,0.335369,0.200305,0.951012,60.714286,22.514405,0.035891,0.077039
721,sunspot,1svr,414.087275,20.349135,32.831193,15.496239,0.50644,0.285696,0.937137,82.142857,25.257897,0.000745,0.038204
725,temperature,1ammeanenscdsrc12k10,7.327568,2.704781,4.769339,2.261728,0.379961,0.137031,0.966779,74.166667,1.76086,inf,inf
722,temperature,1am,7.764751,2.786526,4.923363,2.343869,0.411834,0.151257,0.964111,75.0,2.652628,0.000145,0.079358
743,temperature,1arima,8.875264,2.979138,4.968825,2.358477,0.482584,0.162444,0.96014,79.166667,inf,inf,inf
745,temperature,1as,8.202731,2.864041,4.977129,2.360584,0.395545,0.155971,0.962457,75.0,2.389474,0.000365,0.002747
747,temperature,1asens,7.821548,2.796634,4.942057,2.355732,0.405954,0.149458,0.964129,75.0,2.397749,0.035273,0.097978
760,temperature,1svr,7.130158,2.670235,4.802335,2.308008,0.382437,0.112972,0.970208,79.166667,1.950849,0.000582,0.004552
761,windspeedfortaleza,1am,0.152633,0.390683,11.5419,0.330773,0.715526,0.268302,0.928609,71.428571,0.399669,0.00067,0.055038
782,windspeedfortaleza,1arima,0.159468,0.399335,11.597364,0.337112,0.709828,0.282715,0.924707,57.142857,inf,inf,inf
784,windspeedfortaleza,1as,0.206129,0.454014,13.009162,0.353754,0.532303,0.298071,0.911357,64.285714,0.382258,0.000143,0.001472
786,windspeedfortaleza,1asens,0.218633,0.466934,13.719901,0.382465,0.610503,0.344997,0.900669,56.428571,0.372208,0.025575,0.178652
802,windspeedfortaleza,1svr,0.114718,0.338701,10.062951,0.289563,0.62415,0.264972,0.939855,64.285714,0.367335,0.000259,0.003111
804,windspeednatal,1am,0.115635,0.340051,7.542406,0.29138,1.328906,0.635761,0.84399,57.142857,0.571633,0.000329,0.080705
825,windspeednatal,1arima,0.127373,0.356894,8.198806,0.310429,0.942959,0.66429,0.832185,50.0,inf,inf,inf
827,windspeednatal,1as,0.133393,0.365229,8.124909,0.312721,1.205153,0.736856,0.815178,35.714286,0.582262,0.000135,0.000604
829,windspeednatal,1asens,0.121588,0.348637,7.804535,0.300222,1.134406,0.677186,0.833718,43.571429,0.604353,0.023385,0.030027
845,windspeednatal,1svr,0.177593,0.421418,8.638145,0.328402,1.443301,0.606314,0.804052,57.142857,0.640044,0.000359,0.009024
847,windspeedrecife,1am,0.062368,0.249734,11.679638,0.21223,1.232667,0.485898,0.829181,42.142857,0.268961,0.000335,0.028001
868,windspeedrecife,1arima,0.076085,0.275835,12.525556,0.225836,2.064949,0.572282,0.790966,57.142857,inf,inf,inf
870,windspeedrecife,1as,0.137194,0.370398,16.932665,0.302693,1.217987,0.737609,0.686335,42.857143,0.215278,0.00016,0.013086
872,windspeedrecife,1asens,0.066391,0.257632,11.541109,0.207154,1.81127,0.536322,0.812594,59.285714,0.250195,0.024975,0.036409
889,windspeedrecife,1svr,0.059944,0.244834,10.580556,0.188903,1.830641,0.514563,0.828876,50.0,0.251216,0.000472,0.014386
891,woolyrnq,1am,206464.282627,454.373691,5.901738,307.702576,0.452714,0.474711,0.885601,74.545455,308.750974,0.000212,0.07931
912,woolyrnq,1arima,184439.803464,429.464554,6.33239,312.083418,0.469119,0.476445,0.89298,81.818182,inf,inf,inf
914,woolyrnq,1as,208238.88737,456.331992,7.091572,360.202335,0.422291,0.551918,0.876701,54.545455,333.012599,0.000221,0.000959
916,woolyrnq,1asens,199554.55001,446.655999,6.205228,316.996345,0.482376,0.551196,0.879906,74.545455,312.778128,0.036099,0.10093
929,woolyrnq,1svr,216557.166247,465.357031,6.25638,320.310225,0.43244,0.494294,0.879241,81.818182,343.675422,0.000369,0.001621

[]